export const standardLanguages = [
  "English",
  "Assamese",
  "Bengali",
  "Bodo",
  "Dogri",
  "Gujarati",
  "Hindi",
  "Kannada",
  "Kashmiri",
  "Konkani",
  "Maithili",
  "Malayalam",
  "Manipuri",
  "Marathi",
  "Nepali",
  "Odia",
  "Punjabi",
  "Sanskrit",
  "Santali",
  "Sindhi",
  "Tamil",
  "Telugu",
  "Urdu",
];

export const standardLanguageTextData = {
  English: {
    premiumLabel: "Premium - Siliguri",
    callNow: "Call Now",
    bookConsultation: "Book Consultation",
    exploreServices: "Explore Services",
    whatWeOffer: "What We Offer",
    ourServices: "Our Services",
    shop: "Shop",
    ourProducts: "Our Products",
    viewAll: "View All +",
    orderViaWhatsApp: "Order via WhatsApp",
    gallery: "Gallery",
    getInTouch: "Get In Touch",
    contactUs: "Contact Us",
    contactIntro: "We would love to hear from you. Fill in your details and our team will respond within 24 hours.",
    firstName: "First Name",
    lastName: "Last Name",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    serviceInterestedIn: "Service Interested In",
    message: "Message",
    sendMessage: "Send Message",
    address: "Address",
    phone: "Phone",
    email: "Email",
    hours: "Hours",
    viewOnGoogleMaps: "View on Google Maps",
    chatOnWhatsApp: "Chat on WhatsApp",
    footerLine: "Designed with care - Siliguri, WB",
  },
  Assamese: {
    premiumLabel: "প্ৰিমিয়াম - শিলিগুৰি",
    callNow: "কল কৰক",
    bookConsultation: "পৰামৰ্শ বুক কৰক",
    exploreServices: "সেৱা চাওক",
    whatWeOffer: "আমি কি দিওঁ",
    ourServices: "আমাৰ সেৱা",
    shop: "দোকান",
    ourProducts: "আমাৰ সামগ্ৰী",
    viewAll: "সকলো চাওক +",
    orderViaWhatsApp: "WhatsApp-ত অৰ্ডাৰ",
    gallery: "গেলাৰী",
    getInTouch: "যোগাযোগ কৰক",
    contactUs: "আমাক যোগাযোগ কৰক",
    contactIntro: "আপোনাৰ তথ্য পূৰণ কৰক, আমাৰ দল ২৪ ঘণ্টাৰ ভিতৰত উত্তৰ দিব।",
    firstName: "নাম",
    lastName: "উপাধি",
    emailAddress: "ইমেইল ঠিকনা",
    phoneNumber: "ফোন নম্বৰ",
    serviceInterestedIn: "ৰুচি থকা সেৱা",
    message: "বাৰ্তা",
    sendMessage: "বাৰ্তা পঠাওক",
    address: "ঠিকনা",
    phone: "ফোন",
    email: "ইমেইল",
    hours: "সময়",
    viewOnGoogleMaps: "Google Maps-ত চাওক",
    chatOnWhatsApp: "WhatsApp-ত কথা পাতক",
    footerLine: "যত্নৰে ডিজাইন কৰা - শিলিগুৰি, WB",
  },
  Bengali: {
    premiumLabel: "প্রিমিয়াম - শিলিগুড়ি",
    callNow: "কল করুন",
    bookConsultation: "কনসালটেশন বুক করুন",
    exploreServices: "সেবা দেখুন",
    whatWeOffer: "আমরা যা দিই",
    ourServices: "আমাদের সেবা",
    shop: "শপ",
    ourProducts: "আমাদের প্রোডাক্ট",
    viewAll: "সব দেখুন +",
    orderViaWhatsApp: "WhatsApp-এ অর্ডার",
    gallery: "গ্যালারি",
    getInTouch: "যোগাযোগ করুন",
    contactUs: "আমাদের সাথে যোগাযোগ",
    contactIntro: "আপনার তথ্য দিন, আমাদের টিম ২৪ ঘণ্টার মধ্যে উত্তর দেবে।",
    firstName: "নাম",
    lastName: "পদবি",
    emailAddress: "ইমেইল ঠিকানা",
    phoneNumber: "ফোন নম্বর",
    serviceInterestedIn: "যে সেবায় আগ্রহী",
    message: "মেসেজ",
    sendMessage: "মেসেজ পাঠান",
    address: "ঠিকানা",
    phone: "ফোন",
    email: "ইমেইল",
    hours: "সময়",
    viewOnGoogleMaps: "Google Maps-এ দেখুন",
    chatOnWhatsApp: "WhatsApp-এ চ্যাট",
    footerLine: "যত্ন নিয়ে ডিজাইন - শিলিগুড়ি, WB",
  },
  Bodo: {
    premiumLabel: "प्रिमियाम - सिलिगुड़ि",
    callNow: "कल खालाम",
    bookConsultation: "परामर्श बुक खालाम",
    exploreServices: "सेवा नाय",
    whatWeOffer: "जों मा होयो",
    ourServices: "जोंनि सेवा",
    shop: "दुकान",
    ourProducts: "जोंनि सामान",
    viewAll: "गासै नाय +",
    orderViaWhatsApp: "WhatsApp आव अर्डार",
    gallery: "गेलारी",
    getInTouch: "जोगाजोग खालाम",
    contactUs: "जोंखौ जोगाजोग खालाम",
    contactIntro: "नोंथांनि फोरमायथि हो, जोंनि दले 24 घण्टानि सिङाव फिननाय होगोन।",
    firstName: "मुं",
    lastName: "आखर",
    emailAddress: "इमेल थं",
    phoneNumber: "फोन नाम्बार",
    serviceInterestedIn: "सेवायाव रुचि",
    message: "खौरां",
    sendMessage: "खौरां दैथाय",
    address: "थं",
    phone: "फोन",
    email: "इमेल",
    hours: "सम",
    viewOnGoogleMaps: "Google Maps आव नाय",
    chatOnWhatsApp: "WhatsApp आव रायज्लाय",
    footerLine: "जतनजों डिजाइन - सिलिगुड़ि, WB",
  },
  Dogri: {
    premiumLabel: "प्रीमियम - सिलीगुड़ी",
    callNow: "हुण कॉल करो",
    bookConsultation: "सलाह बुक करो",
    exploreServices: "सेवां वेखो",
    whatWeOffer: "अस के दिंदे आं",
    ourServices: "साडियां सेवां",
    shop: "दुकान",
    ourProducts: "साडे उत्पाद",
    viewAll: "सब वेखो +",
    orderViaWhatsApp: "WhatsApp ते ऑर्डर",
    gallery: "गैलरी",
    getInTouch: "संपर्क करो",
    contactUs: "साडे नाल संपर्क",
    contactIntro: "अपनी जानकारी भरो, साडी टीम 24 घंटे अंदर जवाब देग।",
    firstName: "नां",
    lastName: "उपनां",
    emailAddress: "ईमेल पता",
    phoneNumber: "फोन नंबर",
    serviceInterestedIn: "रुचि वाली सेवा",
    message: "संदेश",
    sendMessage: "संदेश भेजो",
    address: "पता",
    phone: "फोन",
    email: "ईमेल",
    hours: "समां",
    viewOnGoogleMaps: "Google Maps ते वेखो",
    chatOnWhatsApp: "WhatsApp ते चैट",
    footerLine: "ध्यान नाल डिजाइन - सिलीगुड़ी, WB",
  },
  Gujarati: {
    premiumLabel: "પ્રીમિયમ - સિલિગુડી",
    callNow: "હવે કોલ કરો",
    bookConsultation: "કન્સલ્ટેશન બુક કરો",
    exploreServices: "સેવાઓ જુઓ",
    whatWeOffer: "અમે શું આપીએ છીએ",
    ourServices: "અમારી સેવાઓ",
    shop: "શોપ",
    ourProducts: "અમારા પ્રોડક્ટ્સ",
    viewAll: "બધું જુઓ +",
    orderViaWhatsApp: "WhatsApp પર ઓર્ડર",
    gallery: "ગેલેરી",
    getInTouch: "સંપર્કમાં રહો",
    contactUs: "અમારો સંપર્ક કરો",
    contactIntro: "તમારી વિગતો ભરો, અમારી ટીમ 24 કલાકમાં જવાબ આપશે.",
    firstName: "નામ",
    lastName: "અટક",
    emailAddress: "ઇમેઇલ સરનામું",
    phoneNumber: "ફોન નંબર",
    serviceInterestedIn: "રસ ધરાવતી સેવા",
    message: "સંદેશ",
    sendMessage: "સંદેશ મોકલો",
    address: "સરનામું",
    phone: "ફોન",
    email: "ઇમેઇલ",
    hours: "સમય",
    viewOnGoogleMaps: "Google Maps પર જુઓ",
    chatOnWhatsApp: "WhatsApp પર ચેટ",
    footerLine: "કાળજીથી ડિઝાઇન - સિલિગુડી, WB",
  },
  Hindi: {
    premiumLabel: "प्रीमियम - सिलीगुड़ी",
    callNow: "कॉल करें",
    bookConsultation: "कंसल्टेशन बुक करें",
    exploreServices: "सेवाएं देखें",
    whatWeOffer: "हम क्या देते हैं",
    ourServices: "हमारी सेवाएं",
    shop: "शॉप",
    ourProducts: "हमारे प्रोडक्ट",
    viewAll: "सब देखें +",
    orderViaWhatsApp: "WhatsApp पर ऑर्डर",
    gallery: "गैलरी",
    getInTouch: "संपर्क करें",
    contactUs: "हमसे संपर्क करें",
    contactIntro: "अपनी जानकारी भरें, हमारी टीम 24 घंटे में जवाब देगी।",
    firstName: "नाम",
    lastName: "उपनाम",
    emailAddress: "ईमेल पता",
    phoneNumber: "फोन नंबर",
    serviceInterestedIn: "जिस सेवा में रुचि है",
    message: "संदेश",
    sendMessage: "संदेश भेजें",
    address: "पता",
    phone: "फोन",
    email: "ईमेल",
    hours: "समय",
    viewOnGoogleMaps: "Google Maps पर देखें",
    chatOnWhatsApp: "WhatsApp पर चैट",
    footerLine: "ध्यान से डिजाइन - सिलीगुड़ी, WB",
  },
  Kannada: {
    premiumLabel: "ಪ್ರೀಮಿಯಂ - ಸಿಲಿಗುರಿ",
    callNow: "ಕಾಲ್ ಮಾಡಿ",
    bookConsultation: "ಸಲಹೆ ಬುಕ್ ಮಾಡಿ",
    exploreServices: "ಸೇವೆಗಳು ನೋಡಿ",
    whatWeOffer: "ನಾವು ನೀಡುವುದು",
    ourServices: "ನಮ್ಮ ಸೇವೆಗಳು",
    shop: "ಶಾಪ್",
    ourProducts: "ನಮ್ಮ ಉತ್ಪನ್ನಗಳು",
    viewAll: "ಎಲ್ಲ ನೋಡಿ +",
    orderViaWhatsApp: "WhatsApp ನಲ್ಲಿ ಆರ್ಡರ್",
    gallery: "ಗ್ಯಾಲರಿ",
    getInTouch: "ಸಂಪರ್ಕಿಸಿ",
    contactUs: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
    contactIntro: "ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ, ನಮ್ಮ ತಂಡ 24 ಗಂಟೆಯಲ್ಲಿ ಉತ್ತರಿಸುತ್ತದೆ.",
    firstName: "ಹೆಸರು",
    lastName: "ಕುಟುಂಬ ಹೆಸರು",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ",
    serviceInterestedIn: "ಆಸಕ್ತಿ ಇರುವ ಸೇವೆ",
    message: "ಸಂದೇಶ",
    sendMessage: "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    address: "ವಿಳಾಸ",
    phone: "ಫೋನ್",
    email: "ಇಮೇಲ್",
    hours: "ಸಮಯ",
    viewOnGoogleMaps: "Google Maps ನಲ್ಲಿ ನೋಡಿ",
    chatOnWhatsApp: "WhatsApp ನಲ್ಲಿ ಚಾಟ್",
    footerLine: "ಕಾಳಜಿಯಿಂದ ವಿನ್ಯಾಸ - ಸಿಲಿಗುರಿ, WB",
  },
  Kashmiri: {
    premiumLabel: "پریمیم - سلیگوری",
    callNow: "کال کریو",
    bookConsultation: "مشورہ بک کریو",
    exploreServices: "سروسز وچھو",
    whatWeOffer: "أسۍ کیاہ دیتھ",
    ourServices: "أسۍ سروسز",
    shop: "شاپ",
    ourProducts: "أسۍ پراڈکٹس",
    viewAll: "سارے وچھو +",
    orderViaWhatsApp: "WhatsApp پیٹھ آرڈر",
    gallery: "گیلری",
    getInTouch: "رابطہ کریو",
    contactUs: "أسۍ سٲتھ رابطہ",
    contactIntro: "پننۍ تفصیل بھریو، أسۍ ٹیم 24 گھنٹن منز جواب دِیہ۔",
    firstName: "ناو",
    lastName: "خاندانی ناو",
    emailAddress: "ایمیل پتہ",
    phoneNumber: "فون نمبر",
    serviceInterestedIn: "دلچسپی والی سروس",
    message: "پیغام",
    sendMessage: "پیغام بھیجیو",
    address: "پتہ",
    phone: "فون",
    email: "ایمیل",
    hours: "وقت",
    viewOnGoogleMaps: "Google Maps پیٹھ وچھو",
    chatOnWhatsApp: "WhatsApp پیٹھ چیٹ",
    footerLine: "خیال سان ڈیزائن - سلیگوری، WB",
  },
  Konkani: {
    premiumLabel: "प्रीमियम - सिलिगुडी",
    callNow: "कॉल करात",
    bookConsultation: "सलाह बुक करात",
    exploreServices: "सेवा पळयात",
    whatWeOffer: "आमी कितें दितात",
    ourServices: "आमची सेवा",
    shop: "दुकान",
    ourProducts: "आमचे प्रोडक्ट",
    viewAll: "सगळें पळयात +",
    orderViaWhatsApp: "WhatsApp वर ऑर्डर",
    gallery: "गॅलरी",
    getInTouch: "संपर्क करात",
    contactUs: "आमकां संपर्क करात",
    contactIntro: "तुमची माहिती भरात, आमची टीम 24 वरांत जवाब दितली.",
    firstName: "नांव",
    lastName: "आडनांव",
    emailAddress: "ईमेल पत्तो",
    phoneNumber: "फोन नंबर",
    serviceInterestedIn: "रस असलेली सेवा",
    message: "संदेश",
    sendMessage: "संदेश धाडात",
    address: "पत्तो",
    phone: "फोन",
    email: "ईमेल",
    hours: "वेळ",
    viewOnGoogleMaps: "Google Maps वर पळयात",
    chatOnWhatsApp: "WhatsApp वर चॅट",
    footerLine: "काळजीन डिजाइन - सिलिगुडी, WB",
  },
  Maithili: {
    premiumLabel: "प्रीमियम - सिलीगुड़ी",
    callNow: "कॉल करू",
    bookConsultation: "परामर्श बुक करू",
    exploreServices: "सेवा देखू",
    whatWeOffer: "हम की दैत छी",
    ourServices: "हमर सेवा",
    shop: "दुकान",
    ourProducts: "हमर उत्पाद",
    viewAll: "सभ देखू +",
    orderViaWhatsApp: "WhatsApp पर ऑर्डर",
    gallery: "गैलरी",
    getInTouch: "संपर्क करू",
    contactUs: "हमरा सँ संपर्क करू",
    contactIntro: "अपन जानकारी भरू, हमर टीम 24 घंटा में जवाब देत।",
    firstName: "नाम",
    lastName: "उपनाम",
    emailAddress: "ईमेल पता",
    phoneNumber: "फोन नंबर",
    serviceInterestedIn: "जे सेवा में रुचि",
    message: "संदेश",
    sendMessage: "संदेश पठाउ",
    address: "पता",
    phone: "फोन",
    email: "ईमेल",
    hours: "समय",
    viewOnGoogleMaps: "Google Maps पर देखू",
    chatOnWhatsApp: "WhatsApp पर चैट",
    footerLine: "ध्यान सँ डिजाइन - सिलीगुड़ी, WB",
  },
  Malayalam: {
    premiumLabel: "പ്രീമിയം - സിലിഗുരി",
    callNow: "കോൾ ചെയ്യുക",
    bookConsultation: "കൺസൾട്ടേഷൻ ബുക്ക് ചെയ്യുക",
    exploreServices: "സേവനങ്ങൾ കാണുക",
    whatWeOffer: "ഞങ്ങൾ നൽകുന്നത്",
    ourServices: "ഞങ്ങളുടെ സേവനങ്ങൾ",
    shop: "ഷോപ്പ്",
    ourProducts: "ഞങ്ങളുടെ ഉൽപ്പന്നങ്ങൾ",
    viewAll: "എല്ലാം കാണുക +",
    orderViaWhatsApp: "WhatsApp വഴി ഓർഡർ",
    gallery: "ഗാലറി",
    getInTouch: "ബന്ധപ്പെടുക",
    contactUs: "ഞങ്ങളെ ബന്ധപ്പെടുക",
    contactIntro: "നിങ്ങളുടെ വിവരങ്ങൾ പൂരിപ്പിക്കുക, ഞങ്ങളുടെ ടീം 24 മണിക്കൂറിനുള്ളിൽ മറുപടി നൽകും.",
    firstName: "പേര്",
    lastName: "കുടുംബപ്പേര്",
    emailAddress: "ഇമെയിൽ വിലാസം",
    phoneNumber: "ഫോൺ നമ്പർ",
    serviceInterestedIn: "ആസക്തിയുള്ള സേവനം",
    message: "സന്ദേശം",
    sendMessage: "സന്ദേശം അയയ്ക്കുക",
    address: "വിലാസം",
    phone: "ഫോൺ",
    email: "ഇമെയിൽ",
    hours: "സമയം",
    viewOnGoogleMaps: "Google Maps-ൽ കാണുക",
    chatOnWhatsApp: "WhatsApp-ൽ ചാറ്റ്",
    footerLine: "ശ്രദ്ധയോടെ ഡിസൈൻ - സിലിഗുരി, WB",
  },
  Manipuri: {
    premiumLabel: "ꯄ꯭ꯔꯤꯃꯤꯌꯝ - ꯁꯤꯂꯤꯒꯨꯔꯤ",
    callNow: "ꯀꯣꯜ ꯇꯧꯕꯤꯌꯨ",
    bookConsultation: "ꯀꯟꯁꯜꯇꯦꯁꯟ ꯕꯨꯛ ꯇꯧꯕꯤꯌꯨ",
    exploreServices: "ꯁꯔꯚꯤꯁ ꯌꯦꯡꯕꯤꯌꯨ",
    whatWeOffer: "ꯑꯩꯈꯣꯌꯅꯥ ꯀꯔꯤ ꯄꯤꯕꯒꯦ",
    ourServices: "ꯑꯩꯈꯣꯌꯒꯤ ꯁꯔꯚꯤꯁ",
    shop: "ꯁꯣꯞ",
    ourProducts: "ꯑꯩꯈꯣꯌꯒꯤ ꯄ꯭ꯔꯣꯗꯛꯇ",
    viewAll: "ꯄꯨꯝꯅꯃꯛ ꯌꯦꯡꯕꯤꯌꯨ +",
    orderViaWhatsApp: "WhatsApp ꯗꯥ ꯑꯣꯔꯗꯔ",
    gallery: "ꯒꯦꯂꯦꯔꯤ",
    getInTouch: "ꯄꯥꯎ ꯐꯥꯑꯣꯕꯤꯌꯨ",
    contactUs: "ꯑꯩꯈꯣꯌꯒꯥ ꯄꯥꯎ ꯐꯥꯑꯣꯕꯤꯌꯨ",
    contactIntro: "ꯅꯍꯥꯛꯀꯤ ꯋꯥꯔꯣꯜ ꯄꯤꯌꯨ, ꯇꯤꯝꯅꯥ 24 ꯄꯨꯡꯒꯤ ꯃꯅꯨꯡꯗꯥ ꯄꯥꯎꯈꯨꯝ ꯄꯤꯒꯅꯤ।",
    firstName: "ꯃꯤꯡ",
    lastName: "ꯃꯆꯥ ꯃꯤꯡ",
    emailAddress: "ꯏꯃꯦꯜ ꯑꯦꯗ꯭ꯔꯦꯁ",
    phoneNumber: "ꯐꯣꯟ ꯅꯝꯕꯔ",
    serviceInterestedIn: "ꯄꯥꯝꯂꯤꯕ ꯁꯔꯚꯤꯁ",
    message: "ꯃꯦꯁꯦꯖ",
    sendMessage: "ꯃꯦꯁꯦꯖ ꯊꯥꯕꯤꯌꯨ",
    address: "ꯑꯦꯗ꯭ꯔꯦꯁ",
    phone: "ꯐꯣꯟ",
    email: "ꯏꯃꯦꯜ",
    hours: "ꯃꯇꯝ",
    viewOnGoogleMaps: "Google Maps ꯗꯥ ꯌꯦꯡꯕꯤꯌꯨ",
    chatOnWhatsApp: "WhatsApp ꯗꯥ ꯆꯦꯠ",
    footerLine: "ꯆꯤꯡꯅꯕꯥ ꯗꯤꯖꯥꯏꯟ - ꯁꯤꯂꯤꯒꯨꯔꯤ, WB",
  },
  Marathi: {
    premiumLabel: "प्रीमियम - सिलीगुडी",
    callNow: "कॉल करा",
    bookConsultation: "कन्सल्टेशन बुक करा",
    exploreServices: "सेवा पहा",
    whatWeOffer: "आम्ही काय देतो",
    ourServices: "आमच्या सेवा",
    shop: "शॉप",
    ourProducts: "आमची उत्पादने",
    viewAll: "सर्व पहा +",
    orderViaWhatsApp: "WhatsApp वर ऑर्डर",
    gallery: "गॅलरी",
    getInTouch: "संपर्क करा",
    contactUs: "आमच्याशी संपर्क",
    contactIntro: "तुमची माहिती भरा, आमची टीम 24 तासांत उत्तर देईल.",
    firstName: "नाव",
    lastName: "आडनाव",
    emailAddress: "ईमेल पत्ता",
    phoneNumber: "फोन नंबर",
    serviceInterestedIn: "आवड असलेली सेवा",
    message: "संदेश",
    sendMessage: "संदेश पाठवा",
    address: "पत्ता",
    phone: "फोन",
    email: "ईमेल",
    hours: "वेळ",
    viewOnGoogleMaps: "Google Maps वर पहा",
    chatOnWhatsApp: "WhatsApp वर चॅट",
    footerLine: "काळजीपूर्वक डिझाइन - सिलीगुडी, WB",
  },
  Nepali: {
    premiumLabel: "प्रिमियम - सिलिगुडी",
    callNow: "कल गर्नुहोस्",
    bookConsultation: "परामर्श बुक गर्नुहोस्",
    exploreServices: "सेवा हेर्नुहोस्",
    whatWeOffer: "हामी के दिन्छौं",
    ourServices: "हाम्रा सेवाहरू",
    shop: "शप",
    ourProducts: "हाम्रा उत्पादनहरू",
    viewAll: "सबै हेर्नुहोस् +",
    orderViaWhatsApp: "WhatsApp मा अर्डर",
    gallery: "ग्यालरी",
    getInTouch: "सम्पर्कमा आउनुहोस्",
    contactUs: "हामीलाई सम्पर्क गर्नुहोस्",
    contactIntro: "तपाईंको विवरण भर्नुहोस्, हाम्रो टोलीले 24 घण्टाभित्र जवाफ दिनेछ।",
    firstName: "नाम",
    lastName: "थर",
    emailAddress: "इमेल ठेगाना",
    phoneNumber: "फोन नम्बर",
    serviceInterestedIn: "रुचि भएको सेवा",
    message: "सन्देश",
    sendMessage: "सन्देश पठाउनुहोस्",
    address: "ठेगाना",
    phone: "फोन",
    email: "इमेल",
    hours: "समय",
    viewOnGoogleMaps: "Google Maps मा हेर्नुहोस्",
    chatOnWhatsApp: "WhatsApp मा च्याट",
    footerLine: "हेरचाहका साथ डिजाइन - सिलिगुडी, WB",
  },
  Odia: {
    premiumLabel: "ପ୍ରିମିୟମ୍ - ସିଲିଗୁଡି",
    callNow: "କଲ୍ କରନ୍ତୁ",
    bookConsultation: "କନସଲ୍ଟେସନ୍ ବୁକ୍ କରନ୍ତୁ",
    exploreServices: "ସେବା ଦେଖନ୍ତୁ",
    whatWeOffer: "ଆମେ କଣ ଦେଉଛୁ",
    ourServices: "ଆମର ସେବା",
    shop: "ଶପ୍",
    ourProducts: "ଆମର ପ୍ରୋଡକ୍ଟ",
    viewAll: "ସବୁ ଦେଖନ୍ତୁ +",
    orderViaWhatsApp: "WhatsApp ରେ ଅର୍ଡର",
    gallery: "ଗ୍ୟାଲେରୀ",
    getInTouch: "ସମ୍ପର୍କ କରନ୍ତୁ",
    contactUs: "ଆମ ସହ ସମ୍ପର୍କ",
    contactIntro: "ଆପଣଙ୍କ ବିବରଣୀ ଭରନ୍ତୁ, ଆମ ଟିମ୍ 24 ଘଣ୍ଟା ମଧ୍ୟରେ ଉତ୍ତର ଦେବ।",
    firstName: "ନାମ",
    lastName: "ଉପନାମ",
    emailAddress: "ଇମେଲ୍ ଠିକଣା",
    phoneNumber: "ଫୋନ୍ ନମ୍ବର",
    serviceInterestedIn: "ରୁଚିଥିବା ସେବା",
    message: "ବାର୍ତ୍ତା",
    sendMessage: "ବାର୍ତ୍ତା ପଠାନ୍ତୁ",
    address: "ଠିକଣା",
    phone: "ଫୋନ୍",
    email: "ଇମେଲ୍",
    hours: "ସମୟ",
    viewOnGoogleMaps: "Google Maps ରେ ଦେଖନ୍ତୁ",
    chatOnWhatsApp: "WhatsApp ରେ ଚାଟ୍",
    footerLine: "ଯତ୍ନରେ ଡିଜାଇନ୍ - ସିଲିଗୁଡି, WB",
  },
  Punjabi: {
    premiumLabel: "ਪ੍ਰੀਮੀਅਮ - ਸਿਲਿਗੁੜੀ",
    callNow: "ਕਾਲ ਕਰੋ",
    bookConsultation: "ਕਨਸਲਟੇਸ਼ਨ ਬੁੱਕ ਕਰੋ",
    exploreServices: "ਸੇਵਾਵਾਂ ਵੇਖੋ",
    whatWeOffer: "ਅਸੀਂ ਕੀ ਦਿੰਦੇ ਹਾਂ",
    ourServices: "ਸਾਡੀਆਂ ਸੇਵਾਵਾਂ",
    shop: "ਸ਼ਾਪ",
    ourProducts: "ਸਾਡੇ ਪ੍ਰੋਡਕਟ",
    viewAll: "ਸਭ ਵੇਖੋ +",
    orderViaWhatsApp: "WhatsApp ਤੇ ਆਰਡਰ",
    gallery: "ਗੈਲਰੀ",
    getInTouch: "ਸੰਪਰਕ ਕਰੋ",
    contactUs: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ",
    contactIntro: "ਆਪਣੇ ਵੇਰਵੇ ਭਰੋ, ਸਾਡੀ ਟੀਮ 24 ਘੰਟਿਆਂ ਵਿੱਚ ਜਵਾਬ ਦੇਵੇਗੀ।",
    firstName: "ਨਾਮ",
    lastName: "ਅਖੀਰਲਾ ਨਾਮ",
    emailAddress: "ਈਮੇਲ ਪਤਾ",
    phoneNumber: "ਫੋਨ ਨੰਬਰ",
    serviceInterestedIn: "ਰੁਚੀ ਵਾਲੀ ਸੇਵਾ",
    message: "ਸੁਨੇਹਾ",
    sendMessage: "ਸੁਨੇਹਾ ਭੇਜੋ",
    address: "ਪਤਾ",
    phone: "ਫੋਨ",
    email: "ਈਮੇਲ",
    hours: "ਸਮਾਂ",
    viewOnGoogleMaps: "Google Maps ਤੇ ਵੇਖੋ",
    chatOnWhatsApp: "WhatsApp ਤੇ ਚੈਟ",
    footerLine: "ਧਿਆਨ ਨਾਲ ਡਿਜ਼ਾਈਨ - ਸਿਲਿਗੁੜੀ, WB",
  },
  Sanskrit: {
    premiumLabel: "प्रीमियम् - सिलीगुडी",
    callNow: "आह्वानं कुरुत",
    bookConsultation: "परामर्शं आरक्षयत",
    exploreServices: "सेवाः पश्यत",
    whatWeOffer: "वयं किं दद्मः",
    ourServices: "अस्माकं सेवाः",
    shop: "आपणः",
    ourProducts: "अस्माकं उत्पादाः",
    viewAll: "सर्वं पश्यत +",
    orderViaWhatsApp: "WhatsApp द्वारा आदेशः",
    gallery: "चित्रशाला",
    getInTouch: "सम्पर्कं कुरुत",
    contactUs: "अस्मान् सम्पर्कयत",
    contactIntro: "स्वविवरणं पूरयत, अस्माकं दलं 24 घण्टासु प्रत्युत्तरं दास्यति।",
    firstName: "नाम",
    lastName: "कुलनाम",
    emailAddress: "ईमेल-सङ्केतः",
    phoneNumber: "दूरभाष-सङ्ख्या",
    serviceInterestedIn: "रुचिसेवा",
    message: "सन्देशः",
    sendMessage: "सन्देशं प्रेषयत",
    address: "सङ्केतः",
    phone: "दूरभाषः",
    email: "ईमेल",
    hours: "समयः",
    viewOnGoogleMaps: "Google Maps मध्ये पश्यत",
    chatOnWhatsApp: "WhatsApp मध्ये वार्तालापः",
    footerLine: "सावधानतया रूपांकनम् - सिलीगुडी, WB",
  },
  Santali: {
    premiumLabel: "ᱯᱨᱤᱢᱤᱭᱟᱢ - ᱥᱤᱞᱤᱜᱩᱰᱤ",
    callNow: "ᱠᱚᱞ ᱢᱮ",
    bookConsultation: "ᱥᱟᱞᱟᱦ ᱵᱩᱠ ᱢᱮ",
    exploreServices: "ᱥᱮᱵᱟ ᱧᱮᱞ ᱢᱮ",
    whatWeOffer: "ᱟᱞᱮ ᱪᱮᱫ ᱮᱢᱟ",
    ourServices: "ᱟᱞᱮᱭᱟᱜ ᱥᱮᱵᱟ",
    shop: "ᱥᱚᱯ",
    ourProducts: "ᱟᱞᱮᱭᱟᱜ ᱯᱨᱚᱰᱚᱠᱴ",
    viewAll: "ᱡᱷᱚᱛᱚ ᱧᱮᱞ ᱢᱮ +",
    orderViaWhatsApp: "WhatsApp ᱨᱮ ᱚᱨᱰᱚᱨ",
    gallery: "ᱜᱮᱞᱟᱨᱤ",
    getInTouch: "ᱡᱚᱜᱟᱡᱚᱜ ᱢᱮ",
    contactUs: "ᱟᱞᱮ ᱥᱟᱶ ᱡᱚᱜᱟᱡᱚᱜ",
    contactIntro: "ᱟᱢᱟᱜ ᱵᱤᱥᱚᱭ ᱚᱞ ᱢᱮ, ᱟᱞᱮᱭᱟᱜ ᱴᱤᱢ 24 ᱜᱷᱚᱱᱴᱟ ᱨᱮ ᱨᱚᱲ ᱮᱢᱟᱭ।",
    firstName: "ᱧᱩᱛᱩᱢ",
    lastName: "ᱯᱟᱨᱤᱵᱟᱨ ᱧᱩᱛᱩᱢ",
    emailAddress: "ᱤᱢᱮᱞ ᱴᱷᱤᱠᱟᱱᱟ",
    phoneNumber: "ᱯᱷᱚᱱ ᱱᱚᱢᱵᱚᱨ",
    serviceInterestedIn: "ᱯᱟᱥᱱᱟᱣ ᱥᱮᱵᱟ",
    message: "ᱥᱚᱱᱫᱮᱥ",
    sendMessage: "ᱥᱚᱱᱫᱮᱥ ᱠᱩᱞ ᱢᱮ",
    address: "ᱴᱷᱤᱠᱟᱱᱟ",
    phone: "ᱯᱷᱚᱱ",
    email: "ᱤᱢᱮᱞ",
    hours: "ᱚᱠᱛᱚ",
    viewOnGoogleMaps: "Google Maps ᱨᱮ ᱧᱮᱞ ᱢᱮ",
    chatOnWhatsApp: "WhatsApp ᱨᱮ ᱪᱮᱴ",
    footerLine: "ᱫᱤᱥᱟᱹ ᱥᱟᱶ ᱰᱤᱡᱟᱭᱤᱱ - ᱥᱤᱞᱤᱜᱩᱰᱤ, WB",
  },
  Sindhi: {
    premiumLabel: "پريميم - سليگڙي",
    callNow: "ڪال ڪريو",
    bookConsultation: "مشورو بڪ ڪريو",
    exploreServices: "خدمتون ڏسو",
    whatWeOffer: "اسان ڇا ڏيون ٿا",
    ourServices: "اسان جون خدمتون",
    shop: "شاپ",
    ourProducts: "اسان جا پراڊڪٽ",
    viewAll: "سڀ ڏسو +",
    orderViaWhatsApp: "WhatsApp تي آرڊر",
    gallery: "گيلري",
    getInTouch: "رابطو ڪريو",
    contactUs: "اسان سان رابطو",
    contactIntro: "پنهنجا تفصيل ڀريو، اسان جي ٽيم 24 ڪلاڪن ۾ جواب ڏيندي.",
    firstName: "نالو",
    lastName: "آخري نالو",
    emailAddress: "اي ميل پتو",
    phoneNumber: "فون نمبر",
    serviceInterestedIn: "دلچسپي واري خدمت",
    message: "پيغام",
    sendMessage: "پيغام موڪليو",
    address: "پتو",
    phone: "فون",
    email: "اي ميل",
    hours: "وقت",
    viewOnGoogleMaps: "Google Maps تي ڏسو",
    chatOnWhatsApp: "WhatsApp تي چيٽ",
    footerLine: "خيال سان ڊزائين - سليگڙي، WB",
  },
  Tamil: {
    premiumLabel: "பிரீமியம் - சிலிகுரி",
    callNow: "அழைக்கவும்",
    bookConsultation: "ஆலோசனை பதிவு",
    exploreServices: "சேவைகள் பார்க்க",
    whatWeOffer: "நாங்கள் வழங்குவது",
    ourServices: "எங்கள் சேவைகள்",
    shop: "ஷாப்",
    ourProducts: "எங்கள் பொருட்கள்",
    viewAll: "அனைத்தும் பார்க்க +",
    orderViaWhatsApp: "WhatsApp-ல் ஆர்டர்",
    gallery: "கேலரி",
    getInTouch: "தொடர்பு கொள்ள",
    contactUs: "எங்களை தொடர்பு கொள்ள",
    contactIntro: "உங்கள் விவரங்களை நிரப்புங்கள், எங்கள் குழு 24 மணி நேரத்தில் பதில் தரும்.",
    firstName: "பெயர்",
    lastName: "குடும்ப பெயர்",
    emailAddress: "மின்னஞ்சல் முகவரி",
    phoneNumber: "தொலைபேசி எண்",
    serviceInterestedIn: "ஆர்வமுள்ள சேவை",
    message: "செய்தி",
    sendMessage: "செய்தி அனுப்பு",
    address: "முகவரி",
    phone: "தொலைபேசி",
    email: "மின்னஞ்சல்",
    hours: "நேரம்",
    viewOnGoogleMaps: "Google Maps-ல் பார்க்க",
    chatOnWhatsApp: "WhatsApp-ல் அரட்டை",
    footerLine: "கவனத்துடன் வடிவமைப்பு - சிலிகுரி, WB",
  },
  Telugu: {
    premiumLabel: "ప్రీమియం - సిలిగురి",
    callNow: "కాల్ చేయండి",
    bookConsultation: "కన్సల్టేషన్ బుక్ చేయండి",
    exploreServices: "సేవలు చూడండి",
    whatWeOffer: "మేము ఏమి ఇస్తాము",
    ourServices: "మా సేవలు",
    shop: "షాప్",
    ourProducts: "మా ఉత్పత్తులు",
    viewAll: "అన్నీ చూడండి +",
    orderViaWhatsApp: "WhatsApp లో ఆర్డర్",
    gallery: "గ్యాలరీ",
    getInTouch: "సంప్రదించండి",
    contactUs: "మమ్మల్ని సంప్రదించండి",
    contactIntro: "మీ వివరాలు పూరించండి, మా టీమ్ 24 గంటల్లో స్పందిస్తుంది.",
    firstName: "పేరు",
    lastName: "ఇంటి పేరు",
    emailAddress: "ఇమెయిల్ చిరునామా",
    phoneNumber: "ఫోన్ నంబర్",
    serviceInterestedIn: "ఆసక్తి ఉన్న సేవ",
    message: "సందేశం",
    sendMessage: "సందేశం పంపండి",
    address: "చిరునామా",
    phone: "ఫోన్",
    email: "ఇమెయిల్",
    hours: "సమయం",
    viewOnGoogleMaps: "Google Maps లో చూడండి",
    chatOnWhatsApp: "WhatsApp లో చాట్",
    footerLine: "జాగ్రత్తగా డిజైన్ - సిలిగురి, WB",
  },
  Urdu: {
    premiumLabel: "پریمیم - سلیگوری",
    callNow: "کال کریں",
    bookConsultation: "مشاورت بک کریں",
    exploreServices: "خدمات دیکھیں",
    whatWeOffer: "ہم کیا دیتے ہیں",
    ourServices: "ہماری خدمات",
    shop: "شاپ",
    ourProducts: "ہماری مصنوعات",
    viewAll: "سب دیکھیں +",
    orderViaWhatsApp: "WhatsApp پر آرڈر",
    gallery: "گیلری",
    getInTouch: "رابطہ کریں",
    contactUs: "ہم سے رابطہ کریں",
    contactIntro: "اپنی معلومات درج کریں، ہماری ٹیم 24 گھنٹوں میں جواب دے گی۔",
    firstName: "نام",
    lastName: "آخری نام",
    emailAddress: "ای میل پتہ",
    phoneNumber: "فون نمبر",
    serviceInterestedIn: "دلچسپی والی خدمت",
    message: "پیغام",
    sendMessage: "پیغام بھیجیں",
    address: "پتہ",
    phone: "فون",
    email: "ای میل",
    hours: "اوقات",
    viewOnGoogleMaps: "Google Maps پر دیکھیں",
    chatOnWhatsApp: "WhatsApp پر چیٹ",
    footerLine: "خیال سے ڈیزائن - سلیگوری، WB",
  },
};
