import About from "./About";
import Contact from "./Contact";
import FloatingWhatsApp from "./FloatingWhatsApp";
import Gallery from "./Gallery";
import Hero from "./Hero";
import Nav from "./Nav";
import Services from "./Services";
import TemplateStyles from "./TemplateStyles";
import { defaultBusiness, getFontFamily, getHeadingFont } from "./templateData";

export const LABELS = {
  English: {
    callNow: "Call Now",
    getStarted: "Get Started",
    seeServices: "See Services",
    launchPackage: "Lite",
    doctorTitle: "Doctor profile ready",
    doctorText: "Show specialist details, clinic timing, appointment CTA, and patient trust in one premium hero area.",
    servicesKicker: "What We Offer",
    servicesTitle: "Our Services",
    serviceText: "Focused service blocks with clear details, enquiry intent, and a direct conversion path.",
    findUs: "Find Us",
    contactTitle: "Contact & Timing",
    mapTitle: "View on Google Maps",
    gallery: "Gallery",
  },
  Bengali: {
    callNow: "কল করুন",
    getStarted: "শুরু করুন",
    seeServices: "সেবা দেখুন",
    launchPackage: "লঞ্চ প্যাকেজ",
    doctorTitle: "ডাক্তার প্রোফাইল প্রস্তুত",
    doctorText: "বিশেষজ্ঞ তথ্য, ক্লিনিক সময়, অ্যাপয়েন্টমেন্ট CTA এবং রোগীর আস্থা দেখান।",
    servicesKicker: "আমরা যা দিই",
    servicesTitle: "আমাদের সেবা",
    serviceText: "পরিষ্কার তথ্য, দ্রুত enquiry এবং সরাসরি যোগাযোগের জন্য সাজানো সার্ভিস ব্লক।",
    findUs: "আমাদের খুঁজুন",
    contactTitle: "যোগাযোগ ও সময়সূচি",
    mapTitle: "Google Maps-এ দেখুন",
    gallery: "গ্যালারি",
    content: {
      kicker: "একটি ক্লাসিক ব্যবসা স্টাইল",
      title: "বিশ্বাস তৈরি করুন, আরও লিড পান।",
      description: "আপনার সেবা, সময়সূচি, গ্যালারি এবং সরাসরি যোগাযোগ দেখানোর জন্য তৈরি আধুনিক ওয়েবসাইট।",
      aboutKicker: "ব্যবসা সম্পর্কে",
      aboutTitle: "যেখানে মান আর বিশ্বাস একসাথে",
      about: "এই ডিজাইনটি স্থানীয় ব্যবসার জন্য তৈরি, যাতে সেবা সুন্দরভাবে বোঝানো যায় এবং গ্রাহক সহজে যোগাযোগ করতে পারে।",
      services: ["প্রধান সেবা", "প্রিমিয়াম সেবা", "পরামর্শ", "বুকিং সাপোর্ট", "কাস্টমার কেয়ার", "WhatsApp লিড"],
      stats: [["6+", "বছরের অভিজ্ঞতা"], ["12", "বিশেষজ্ঞ টিম"], ["98%", "গ্রাহক সন্তুষ্টি"]],
      galleryTitle: "ব্র্যান্ডের ভিতরের ঝলক",
      mapNote: "কল, enquiry, booking এবং WhatsApp lead-এর জন্য উপযুক্ত।",
    },
  },
  Hindi: {
    callNow: "कॉल करें",
    getStarted: "शुरू करें",
    seeServices: "सेवाएं देखें",
    launchPackage: "लॉन्च पैकेज",
    doctorTitle: "डॉक्टर प्रोफाइल तैयार",
    doctorText: "विशेषज्ञ जानकारी, क्लिनिक समय, अपॉइंटमेंट CTA और भरोसा दिखाएं।",
    servicesKicker: "हम क्या देते हैं",
    servicesTitle: "हमारी सेवाएं",
    serviceText: "स्पष्ट जानकारी, enquiry intent और direct conversion path वाले service blocks.",
    findUs: "हमें खोजें",
    contactTitle: "संपर्क और समय",
    mapTitle: "Google Maps पर देखें",
    gallery: "गैलरी",
    content: {
      kicker: "एक क्लासिक बिजनेस स्टाइल",
      title: "भरोसा बनाएं, ज्यादा लीड पाएं।",
      description: "सेवाएं, समय, गैलरी और सीधे संपर्क दिखाने के लिए बनाया गया आधुनिक वेबसाइट लेआउट।",
      aboutKicker: "बिजनेस के बारे में",
      aboutTitle: "जहां गुणवत्ता और भरोसा मिलते हैं",
      about: "यह डिजाइन local businesses के लिए है ताकि वे अपनी सेवाएं साफ दिखा सकें और customers आसानी से संपर्क कर सकें।",
      services: ["मुख्य सेवा", "प्रीमियम सेवा", "सलाह", "बुकिंग सपोर्ट", "कस्टमर केयर", "WhatsApp लीड"],
      stats: [["6+", "साल का अनुभव"], ["12", "विशेषज्ञ टीम"], ["98%", "ग्राहक संतुष्टि"]],
      galleryTitle: "ब्रांड की झलक",
      mapNote: "कॉल, enquiry, booking और WhatsApp leads के लिए उपयुक्त।",
    },
  },
  Spanish: {
    callNow: "Llamar",
    getStarted: "Empezar",
    seeServices: "Ver servicios",
    launchPackage: "Paquete inicial",
    doctorTitle: "Perfil medico listo",
    doctorText: "Muestra detalles, horarios, cita y confianza del paciente.",
    servicesKicker: "Que ofrecemos",
    servicesTitle: "Servicios",
    serviceText: "Bloques claros con detalles, intencion de consulta y ruta directa de conversion.",
    findUs: "Encuentranos",
    contactTitle: "Contacto y horario",
    mapTitle: "Ver en Google Maps",
    gallery: "Galeria",
    content: {
      kicker: "Un estilo clasico de negocio",
      title: "Crea confianza y consigue mas clientes.",
      description: "Un sitio moderno para mostrar servicios, horarios, galeria y contacto directo.",
      aboutKicker: "Sobre el negocio",
      aboutTitle: "Donde calidad y confianza se unen",
      about: "Disenado para negocios locales que quieren explicar sus servicios y recibir consultas rapidamente.",
      services: ["Servicio principal", "Servicio premium", "Consulta", "Reservas", "Atencion al cliente", "Leads por WhatsApp"],
      stats: [["6+", "Anos de experiencia"], ["12", "Equipo experto"], ["98%", "Clientes satisfechos"]],
      galleryTitle: "Dentro de la marca",
      mapNote: "Ideal para llamadas, consultas, reservas y leads por WhatsApp.",
    },
  },
  French: {
    callNow: "Appeler",
    getStarted: "Commencer",
    seeServices: "Voir services",
    launchPackage: "Pack lancement",
    doctorTitle: "Profil docteur pret",
    doctorText: "Affiche les details, horaires, rendez-vous et confiance patient.",
    servicesKicker: "Ce que nous offrons",
    servicesTitle: "Nos services",
    serviceText: "Des blocs clairs avec details, intention de contact et chemin de conversion direct.",
    findUs: "Nous trouver",
    contactTitle: "Contact et horaires",
    mapTitle: "Voir sur Google Maps",
    gallery: "Galerie",
    content: {
      kicker: "Un style business classique",
      title: "Creez la confiance et gagnez plus de prospects.",
      description: "Un site moderne pour presenter services, horaires, galerie et contact direct.",
      aboutKicker: "A propos",
      aboutTitle: "La qualite rencontre la confiance",
      about: "Concu pour les entreprises locales qui veulent expliquer leurs services et recevoir des demandes rapidement.",
      services: ["Service principal", "Service premium", "Conseil", "Reservation", "Support client", "Prospects WhatsApp"],
      stats: [["6+", "Annees d'experience"], ["12", "Equipe experte"], ["98%", "Clients satisfaits"]],
      galleryTitle: "Dans la marque",
      mapNote: "Parfait pour les appels, demandes, reservations et prospects WhatsApp.",
    },
  },
  Arabic: {
    callNow: "اتصل الآن",
    getStarted: "ابدأ",
    seeServices: "عرض الخدمات",
    launchPackage: "باقة الإطلاق",
    doctorTitle: "ملف الطبيب جاهز",
    doctorText: "اعرض التفاصيل والمواعيد والثقة وحجز المرضى.",
    servicesKicker: "ماذا نقدم",
    servicesTitle: "خدماتنا",
    serviceText: "مربعات خدمة واضحة مع تفاصيل ومسار تواصل مباشر.",
    findUs: "اعثر علينا",
    contactTitle: "التواصل والمواعيد",
    mapTitle: "عرض على خرائط Google",
    gallery: "المعرض",
    content: {
      kicker: "نمط عمل كلاسيكي",
      title: "ابن الثقة واحصل على عملاء أكثر.",
      description: "موقع حديث لعرض الخدمات والمواعيد والمعرض والتواصل المباشر.",
      aboutKicker: "عن العمل",
      aboutTitle: "حيث تلتقي الجودة بالثقة",
      about: "مصمم للأعمال المحلية لشرح الخدمات بوضوح ومساعدة العملاء على التواصل بسرعة.",
      services: ["الخدمة الأساسية", "خدمة مميزة", "استشارة", "دعم الحجز", "خدمة العملاء", "عملاء WhatsApp"],
      stats: [["6+", "سنوات خبرة"], ["12", "فريق خبير"], ["98%", "رضا العملاء"]],
      galleryTitle: "داخل العلامة",
      mapNote: "مناسب للمكالمات والاستفسارات والحجوزات وعملاء WhatsApp.",
    },
  },
  Nepali: {
    callNow: "कल गर्नुहोस्",
    getStarted: "सुरु गर्नुहोस्",
    seeServices: "सेवा हेर्नुहोस्",
    launchPackage: "लन्च प्याकेज",
    doctorTitle: "डाक्टर प्रोफाइल तयार",
    doctorText: "विशेषज्ञ विवरण, समय, अपोइन्टमेन्ट CTA र विश्वास देखाउनुहोस्।",
    servicesKicker: "हामी के दिन्छौं",
    servicesTitle: "हाम्रा सेवाहरू",
    serviceText: "स्पष्ट जानकारी, enquiry intent र direct conversion path भएको सेवा ब्लक।",
    findUs: "हामीलाई भेट्नुहोस्",
    contactTitle: "सम्पर्क र समय",
    mapTitle: "Google Maps मा हेर्नुहोस्",
    gallery: "ग्यालरी",
    content: {
      kicker: "एक क्लासिक व्यवसाय शैली",
      title: "विश्वास बनाउनुहोस्, बढी लिड पाउनुहोस्।",
      description: "सेवा, समय, ग्यालरी र प्रत्यक्ष सम्पर्क देखाउन बनाइएको आधुनिक वेबसाइट।",
      aboutKicker: "व्यवसाय बारे",
      aboutTitle: "जहाँ गुणस्तर र विश्वास भेटिन्छ",
      about: "स्थानीय व्यवसायका लागि बनाइएको डिजाइन, जसले सेवा स्पष्ट देखाउँछ र ग्राहकलाई छिटो सम्पर्क गर्न मद्दत गर्छ।",
      services: ["मुख्य सेवा", "प्रिमियम सेवा", "परामर्श", "बुकिङ सपोर्ट", "ग्राहक सेवा", "WhatsApp लिड"],
      stats: [["6+", "वर्षको अनुभव"], ["12", "विशेषज्ञ टोली"], ["98%", "ग्राहक सन्तुष्टि"]],
      galleryTitle: "ब्रान्ड भित्र",
      mapNote: "कल, enquiry, booking र WhatsApp leads का लागि उपयुक्त।",
    },
  },
};

function createIndianLabels(copy) {
  return {
    callNow: copy.callNow,
    getStarted: copy.getStarted,
    seeServices: copy.seeServices,
    launchPackage: copy.launchPackage,
    doctorTitle: copy.doctorTitle,
    doctorText: copy.doctorText,
    servicesKicker: copy.servicesKicker,
    servicesTitle: copy.servicesTitle,
    serviceText: copy.serviceText,
    findUs: copy.findUs,
    contactTitle: copy.contactTitle,
    mapTitle: copy.mapTitle,
    gallery: copy.gallery,
    content: {
      kicker: copy.kicker,
      title: copy.title,
      description: copy.description,
      aboutKicker: copy.aboutKicker,
      aboutTitle: copy.aboutTitle,
      about: copy.about,
      services: copy.services,
      stats: copy.stats,
      galleryTitle: copy.galleryTitle,
      mapNote: copy.mapNote,
    },
  };
}

Object.assign(LABELS, {
  Assamese: createIndianLabels({
    callNow: "কল কৰক",
    getStarted: "আৰম্ভ কৰক",
    seeServices: "সেৱা চাওক",
    launchPackage: "লঞ্চ পেকেজ",
    doctorTitle: "প্ৰফাইল সাজু",
    doctorText: "বিশেষজ্ঞ তথ্য, সময়, বুকিং CTA আৰু বিশ্বাস একে ঠাইত দেখুৱাওক।",
    servicesKicker: "আমি কি দিওঁ",
    servicesTitle: "আমাৰ সেৱাসমূহ",
    serviceText: "স্পষ্ট তথ্য, enquiry আৰু সহজ যোগাযোগৰ বাবে সাজু সেৱা ব্লক।",
    findUs: "আমাক বিচাৰক",
    contactTitle: "যোগাযোগ আৰু সময়",
    mapTitle: "Google Maps ত চাওক",
    gallery: "গেলাৰী",
    kicker: "এটা ক্লাছিক ব্যৱসায় শৈলী",
    title: "বিশ্বাস গঢ়ক, অধিক লিড পাওক।",
    description: "সেৱা, সময়সূচী, গেলাৰী আৰু সরাসৰি যোগাযোগ দেখুৱাবলৈ আধুনিক ৱেবছাইট।",
    aboutKicker: "ব্যৱসায়ৰ বিষয়ে",
    aboutTitle: "য’ত মান আৰু বিশ্বাস একেলগে থাকে",
    about: "স্থানীয় ব্যৱসায়ৰ বাবে তৈয়াৰ ডিজাইন, যাতে সেৱা স্পষ্ট হয় আৰু গ্ৰাহকে সহজে যোগাযোগ কৰে।",
    services: ["মুখ্য সেৱা", "প্ৰিমিয়াম সেৱা", "পৰামৰ্শ", "বুকিং সহায়", "গ্ৰাহক সেৱা", "WhatsApp লিড"],
    stats: [["6+", "বছৰৰ অভিজ্ঞতা"], ["12", "বিশেষজ্ঞ দল"], ["98%", "গ্ৰাহক সন্তুষ্টি"]],
    galleryTitle: "ব্ৰেণ্ডৰ ভিতৰৰ ঝলক",
    mapNote: "কল, enquiry, booking আৰু WhatsApp lead ৰ বাবে উপযুক্ত।",
  }),
  Bengali: createIndianLabels({
    callNow: "কল করুন",
    getStarted: "শুরু করুন",
    seeServices: "সেবা দেখুন",
    launchPackage: "লঞ্চ প্যাকেজ",
    doctorTitle: "প্রোফাইল প্রস্তুত",
    doctorText: "বিশেষজ্ঞ তথ্য, সময়, বুকিং CTA এবং বিশ্বাস এক জায়গায় দেখান।",
    servicesKicker: "আমরা যা দিই",
    servicesTitle: "আমাদের সেবা",
    serviceText: "পরিষ্কার তথ্য, enquiry এবং সহজ যোগাযোগের জন্য সাজানো সার্ভিস ব্লক।",
    findUs: "আমাদের খুঁজুন",
    contactTitle: "যোগাযোগ ও সময়সূচি",
    mapTitle: "Google Maps-এ দেখুন",
    gallery: "গ্যালারি",
    kicker: "একটি ক্লাসিক ব্যবসা স্টাইল",
    title: "বিশ্বাস তৈরি করুন, আরও লিড পান।",
    description: "আপনার সেবা, সময়সূচি, গ্যালারি এবং সরাসরি যোগাযোগ দেখানোর জন্য তৈরি আধুনিক ওয়েবসাইট।",
    aboutKicker: "ব্যবসা সম্পর্কে",
    aboutTitle: "যেখানে মান আর বিশ্বাস একসাথে",
    about: "এই ডিজাইনটি স্থানীয় ব্যবসার জন্য তৈরি, যাতে সেবা সুন্দরভাবে বোঝানো যায় এবং গ্রাহক সহজে যোগাযোগ করতে পারে।",
    services: ["প্রধান সেবা", "প্রিমিয়াম সেবা", "পরামর্শ", "বুকিং সাপোর্ট", "কাস্টমার কেয়ার", "WhatsApp লিড"],
    stats: [["6+", "বছরের অভিজ্ঞতা"], ["12", "বিশেষজ্ঞ টিম"], ["98%", "গ্রাহক সন্তুষ্টি"]],
    galleryTitle: "ব্র্যান্ডের ভিতরের ঝলক",
    mapNote: "কল, enquiry, booking এবং WhatsApp lead-এর জন্য উপযুক্ত।",
  }),
  Bodo: createIndianLabels({
    callNow: "कल खालाम",
    getStarted: "जागाय",
    seeServices: "सेवा नाय",
    launchPackage: "लन्च पेकेज",
    doctorTitle: "प्रोफाइल थियारि",
    doctorText: "विशेषज्ञ फोरमायथि, सम, बुकिंग CTA आरो फोथायथि दिन्थि।",
    servicesKicker: "जों मा होयो",
    servicesTitle: "जोंनि सेवा",
    serviceText: "गुवारै फोरमायथि, enquiry आरो गोरलै जोगाजोगनि थाखाय सेवा ब्लक।",
    findUs: "जोंखौ नागिर",
    contactTitle: "जोगाजोग आरो सम",
    mapTitle: "Google Maps आव नाय",
    gallery: "गेलारी",
    kicker: "मोनसे क्लासिक बिजनेस स्टाइल",
    title: "फोथायथि दा, गोबां लिड मोन।",
    description: "सेवा, सम, गेलारी आरो सोझा जोगाजोग दिन्थिनो आधुनिक वेबसाइट।",
    aboutKicker: "बिजनेसनि सोमोन्दै",
    aboutTitle: "मान आरो फोथायथि लोगोसे",
    about: "थाखोमानि बिजनेसनि थाखाय डिजाइन, सेवा गुवारै दिन्थि आरो ग्राहक गोरलै जोगाजोग खालामो।",
    services: ["मुख्य सेवा", "प्रिमियम सेवा", "सलाह", "बुकिंग सपोर्ट", "ग्राहक सेवा", "WhatsApp लिड"],
    stats: [["6+", "बोसोरनि अनुभव"], ["12", "विशेषज्ञ दल"], ["98%", "ग्राहक संतुष्टि"]],
    galleryTitle: "ब्रान्डनि झलक",
    mapNote: "कल, enquiry, booking आरो WhatsApp leads नि थाखाय गनायथि।",
  }),
  Dogri: createIndianLabels({
    callNow: "कॉल करो",
    getStarted: "शुरू करो",
    seeServices: "सेवाएं देखो",
    launchPackage: "लॉन्च पैकेज",
    doctorTitle: "प्रोफाइल तयार",
    doctorText: "विशेषज्ञ जानकारी, समय, बुकिंग CTA ते भरोसा इक जगह दिखाओ।",
    servicesKicker: "अस की दिन्ने आं",
    servicesTitle: "साढ़ियां सेवाएं",
    serviceText: "साफ जानकारी, enquiry ते आसान संपर्क आस्तै सेवा ब्लॉक।",
    findUs: "साढ़े नाल जुड़ो",
    contactTitle: "संपर्क ते समय",
    mapTitle: "Google Maps ते देखो",
    gallery: "गैलरी",
    kicker: "इक क्लासिक बिजनेस स्टाइल",
    title: "भरोसा बनाओ, होर लीड पाओ।",
    description: "सेवाएं, समय, गैलरी ते सीधा संपर्क दिखाण आस्तै आधुनिक वेबसाइट।",
    aboutKicker: "बिजनेस बारे",
    aboutTitle: "जित्थे गुणवत्ता ते भरोसा मिलदे न",
    about: "स्थानीय बिजनेस आस्तै डिजाइन, जेड़ा सेवाएं साफ दिखांदा ते ग्राहक नू जल्दी संपर्क करवांदा।",
    services: ["मुख्य सेवा", "प्रीमियम सेवा", "सलाह", "बुकिंग सपोर्ट", "ग्राहक सेवा", "WhatsApp लीड"],
    stats: [["6+", "साल दा अनुभव"], ["12", "विशेषज्ञ टीम"], ["98%", "ग्राहक संतुष्टि"]],
    galleryTitle: "ब्रांड दी झलक",
    mapNote: "कॉल, enquiry, booking ते WhatsApp leads आस्तै उपयुक्त।",
  }),
  Gujarati: createIndianLabels({
    callNow: "કૉલ કરો",
    getStarted: "શરૂ કરો",
    seeServices: "સેવાઓ જુઓ",
    launchPackage: "લોન્ચ પેકેજ",
    doctorTitle: "પ્રોફાઇલ તૈયાર",
    doctorText: "વિશેષજ્ઞ માહિતી, સમય, બુકિંગ CTA અને વિશ્વાસ એક જગ્યાએ બતાવો.",
    servicesKicker: "અમે શું આપીએ",
    servicesTitle: "અમારી સેવાઓ",
    serviceText: "સ્પષ્ટ માહિતી, enquiry અને સરળ સંપર્ક માટે તૈયાર સેવા બ્લોક.",
    findUs: "અમને શોધો",
    contactTitle: "સંપર્ક અને સમય",
    mapTitle: "Google Maps પર જુઓ",
    gallery: "ગેલેરી",
    kicker: "એક ક્લાસિક બિઝનેસ સ્ટાઇલ",
    title: "વિશ્વાસ બનાવો, વધુ લીડ મેળવો.",
    description: "સેવાઓ, સમય, ગેલેરી અને સીધો સંપર્ક બતાવવા માટે આધુનિક વેબસાઇટ.",
    aboutKicker: "બિઝનેસ વિશે",
    aboutTitle: "જ્યાં ગુણવત્તા અને વિશ્વાસ મળે છે",
    about: "સ્થાનિક બિઝનેસ માટે બનાવેલ ડિઝાઇન, જેથી સેવા સ્પષ્ટ દેખાય અને ગ્રાહક સરળતાથી સંપર્ક કરે.",
    services: ["મુખ્ય સેવા", "પ્રીમિયમ સેવા", "સલાહ", "બુકિંગ સપોર્ટ", "ગ્રાહક સેવા", "WhatsApp લીડ"],
    stats: [["6+", "વર્ષનો અનુભવ"], ["12", "વિશેષજ્ઞ ટીમ"], ["98%", "ગ્રાહક સંતોષ"]],
    galleryTitle: "બ્રાન્ડની ઝલક",
    mapNote: "કૉલ, enquiry, booking અને WhatsApp leads માટે યોગ્ય.",
  }),
  Hindi: createIndianLabels({
    callNow: "कॉल करें",
    getStarted: "शुरू करें",
    seeServices: "सेवाएं देखें",
    launchPackage: "लॉन्च पैकेज",
    doctorTitle: "प्रोफाइल तैयार",
    doctorText: "विशेषज्ञ जानकारी, समय, बुकिंग CTA और भरोसा एक जगह दिखाएं।",
    servicesKicker: "हम क्या देते हैं",
    servicesTitle: "हमारी सेवाएं",
    serviceText: "स्पष्ट जानकारी, enquiry और आसान संपर्क के लिए तैयार सेवा ब्लॉक।",
    findUs: "हमें खोजें",
    contactTitle: "संपर्क और समय",
    mapTitle: "Google Maps पर देखें",
    gallery: "गैलरी",
    kicker: "एक क्लासिक बिजनेस स्टाइल",
    title: "भरोसा बनाएं, ज्यादा लीड पाएं।",
    description: "सेवाएं, समय, गैलरी और सीधे संपर्क दिखाने के लिए बनाया गया आधुनिक वेबसाइट लेआउट।",
    aboutKicker: "बिजनेस के बारे में",
    aboutTitle: "जहां गुणवत्ता और भरोसा मिलते हैं",
    about: "स्थानीय बिजनेस के लिए डिजाइन, ताकि सेवाएं साफ दिखें और ग्राहक आसानी से संपर्क कर सकें।",
    services: ["मुख्य सेवा", "प्रीमियम सेवा", "सलाह", "बुकिंग सपोर्ट", "ग्राहक सेवा", "WhatsApp लीड"],
    stats: [["6+", "साल का अनुभव"], ["12", "विशेषज्ञ टीम"], ["98%", "ग्राहक संतुष्टि"]],
    galleryTitle: "ब्रांड की झलक",
    mapNote: "कॉल, enquiry, booking और WhatsApp leads के लिए उपयुक्त।",
  }),
  Kannada: createIndianLabels({
    callNow: "ಕಾಲ್ ಮಾಡಿ",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    seeServices: "ಸೇವೆಗಳು ನೋಡಿ",
    launchPackage: "ಲಾಂಚ್ ಪ್ಯಾಕೇಜ್",
    doctorTitle: "ಪ್ರೊಫೈಲ್ ಸಿದ್ಧ",
    doctorText: "ತಜ್ಞರ ಮಾಹಿತಿ, ಸಮಯ, ಬುಕಿಂಗ್ CTA ಮತ್ತು ನಂಬಿಕೆಯನ್ನು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ತೋರಿಸಿ.",
    servicesKicker: "ನಾವು ಏನು ನೀಡುತ್ತೇವೆ",
    servicesTitle: "ನಮ್ಮ ಸೇವೆಗಳು",
    serviceText: "ಸ್ಪಷ್ಟ ಮಾಹಿತಿ, enquiry ಮತ್ತು ಸುಲಭ ಸಂಪರ್ಕಕ್ಕಾಗಿ ಸಿದ್ಧ ಸೇವಾ ಬ್ಲಾಕ್.",
    findUs: "ನಮ್ಮನ್ನು ಹುಡುಕಿ",
    contactTitle: "ಸಂಪರ್ಕ ಮತ್ತು ಸಮಯ",
    mapTitle: "Google Maps ನಲ್ಲಿ ನೋಡಿ",
    gallery: "ಗ್ಯಾಲರಿ",
    kicker: "ಒಂದು ಕ್ಲಾಸಿಕ್ ಬಿಸಿನೆಸ್ ಶೈಲಿ",
    title: "ನಂಬಿಕೆ ನಿರ್ಮಿಸಿ, ಹೆಚ್ಚು ಲೀಡ್ ಪಡೆಯಿರಿ.",
    description: "ಸೇವೆಗಳು, ಸಮಯ, ಗ್ಯಾಲರಿ ಮತ್ತು ನೇರ ಸಂಪರ್ಕ ತೋರಿಸಲು ಆಧುನಿಕ ವೆಬ್‌ಸೈಟ್.",
    aboutKicker: "ಬಿಸಿನೆಸ್ ಬಗ್ಗೆ",
    aboutTitle: "ಗುಣಮಟ್ಟ ಮತ್ತು ನಂಬಿಕೆ ಸೇರುವ ಸ್ಥಳ",
    about: "ಸ್ಥಳೀಯ ಬಿಸಿನೆಸ್‌ಗಾಗಿ ವಿನ್ಯಾಸ, ಸೇವೆಗಳನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ತೋರಿಸಿ ಗ್ರಾಹಕರು ಸುಲಭವಾಗಿ ಸಂಪರ್ಕಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
    services: ["ಮುಖ್ಯ ಸೇವೆ", "ಪ್ರೀಮಿಯಂ ಸೇವೆ", "ಸಲಹೆ", "ಬುಕಿಂಗ್ ಸಹಾಯ", "ಗ್ರಾಹಕ ಸೇವೆ", "WhatsApp ಲೀಡ್"],
    stats: [["6+", "ವರ್ಷಗಳ ಅನುಭವ"], ["12", "ತಜ್ಞ ತಂಡ"], ["98%", "ಗ್ರಾಹಕ ತೃಪ್ತಿ"]],
    galleryTitle: "ಬ್ರ್ಯಾಂಡ್‌ನ ಒಳನೋಟ",
    mapNote: "ಕಾಲ್, enquiry, booking ಮತ್ತು WhatsApp leads ಗೆ ಸೂಕ್ತ.",
  }),
  Kashmiri: createIndianLabels({
    callNow: "کال کٔریو",
    getStarted: "شروع کٔریو",
    seeServices: "سروس وُچھو",
    launchPackage: "لانچ پیکیج",
    doctorTitle: "پروفائل تیار",
    doctorText: "ماہر معلومات، وقت، بکنگ CTA تہٕ اعتماد اکھ جایہ وُچھاون۔",
    servicesKicker: "اسی کیا دِوان",
    servicesTitle: "اسانٛز خدمات",
    serviceText: "صاف معلومات، enquiry تہٕ آسان رابطہ خٲطر خدمت بلاک۔",
    findUs: "اسان تلاش کٔریو",
    contactTitle: "رابطہ تہٕ وقت",
    mapTitle: "Google Maps پٲٹھۍ وُچھو",
    gallery: "گیلری",
    kicker: "اکھ کلاسک بزنس سٹائل",
    title: "اعتماد بناوو، زیادٕ لیڈ حاصل کٔریو۔",
    description: "خدمات، وقت، گیلری تہٕ سیدھا رابطہ وُچھاونہٕ خٲطر جدید ویب سائٹ۔",
    aboutKicker: "بزنس بابت",
    aboutTitle: "یتھ معیار تہٕ اعتماد ملان چھ",
    about: "مقامی بزنس خٲطر ڈیزائن، یم خدمات صاف وُچھاون تہٕ گاہک آسانی سان رابطہ کرن۔",
    services: ["اہم خدمت", "پریمیم خدمت", "مشورہ", "بکنگ سپورٹ", "گاہک خدمت", "WhatsApp لیڈ"],
    stats: [["6+", "سال تجربہ"], ["12", "ماہر ٹیم"], ["98%", "گاہک خوشی"]],
    galleryTitle: "برانڈ ہُند جھلک",
    mapNote: "کال، enquiry، booking تہٕ WhatsApp leads خٲطر مناسب۔",
  }),
  Konkani: createIndianLabels({
    callNow: "कॉल करात",
    getStarted: "सुरू करात",
    seeServices: "सेवा पळयात",
    launchPackage: "लॉन्च पॅकेज",
    doctorTitle: "प्रोफाइल तयार",
    doctorText: "तज्ञ माहिती, वेळ, बुकिंग CTA आनी विश्वास एका जाग्यार दाखयात.",
    servicesKicker: "आमी कितें दितात",
    servicesTitle: "आमच्या सेवा",
    serviceText: "स्पष्ट माहिती, enquiry आनी सोप्या संपर्काखातीर सेवा ब्लॉक.",
    findUs: "आमका सोदात",
    contactTitle: "संपर्क आनी वेळ",
    mapTitle: "Google Maps चेर पळयात",
    gallery: "गॅलरी",
    kicker: "एक क्लासिक बिजनेस स्टाइल",
    title: "विश्वास तयार करात, चड लीड मेळयात.",
    description: "सेवा, वेळ, गॅलरी आनी थेट संपर्क दाखवपाखातीर आधुनिक वेबसाइट.",
    aboutKicker: "बिजनेस विशीं",
    aboutTitle: "जंय गुणवत्ता आनी विश्वास मेळटा",
    about: "स्थानिक बिजनेस खातीर तयार डिजाइन, ज्यान सेवा स्पष्ट दिसतात आनी ग्राहक सहज संपर्क करतात.",
    services: ["मुख्य सेवा", "प्रीमियम सेवा", "सल्लो", "बुकिंग सपोर्ट", "ग्राहक सेवा", "WhatsApp लीड"],
    stats: [["6+", "वर्सांचो अनुभव"], ["12", "तज्ञ टीम"], ["98%", "ग्राहक समाधान"]],
    galleryTitle: "ब्रांडाची झलक",
    mapNote: "कॉल, enquiry, booking आनी WhatsApp leads खातीर योग्य.",
  }),
  Maithili: createIndianLabels({
    callNow: "कॉल करू",
    getStarted: "शुरू करू",
    seeServices: "सेवा देखू",
    launchPackage: "लॉन्च पैकेज",
    doctorTitle: "प्रोफाइल तैयार",
    doctorText: "विशेषज्ञ जानकारी, समय, बुकिंग CTA आ भरोसा एक ठाम देखाउ।",
    servicesKicker: "हम की दैत छी",
    servicesTitle: "हमर सेवा",
    serviceText: "स्पष्ट जानकारी, enquiry आ सहज संपर्क लेल सेवा ब्लॉक।",
    findUs: "हमरा खोजू",
    contactTitle: "संपर्क आ समय",
    mapTitle: "Google Maps पर देखू",
    gallery: "गैलरी",
    kicker: "एक क्लासिक बिजनेस स्टाइल",
    title: "भरोसा बनाउ, बेसी लीड पाउ।",
    description: "सेवा, समय, गैलरी आ सीधा संपर्क देखाबय लेल आधुनिक वेबसाइट।",
    aboutKicker: "बिजनेस के बारे में",
    aboutTitle: "जतय गुणवत्ता आ भरोसा भेटैत अछि",
    about: "स्थानीय बिजनेस लेल डिजाइन, जाहि सँ सेवा साफ देखाइ आ ग्राहक सहज संपर्क करथि।",
    services: ["मुख्य सेवा", "प्रीमियम सेवा", "सलाह", "बुकिंग सपोर्ट", "ग्राहक सेवा", "WhatsApp लीड"],
    stats: [["6+", "सालक अनुभव"], ["12", "विशेषज्ञ टीम"], ["98%", "ग्राहक संतुष्टि"]],
    galleryTitle: "ब्रांडक झलक",
    mapNote: "कॉल, enquiry, booking आ WhatsApp leads लेल उपयुक्त।",
  }),
  Malayalam: createIndianLabels({
    callNow: "കോൾ ചെയ്യൂ",
    getStarted: "തുടങ്ങൂ",
    seeServices: "സേവനങ്ങൾ കാണൂ",
    launchPackage: "ലോഞ്ച് പാക്കേജ്",
    doctorTitle: "പ്രൊഫൈൽ തയ്യാറാണ്",
    doctorText: "വിദഗ്ധ വിവരം, സമയം, ബുക്കിംഗ് CTA, വിശ്വാസം എന്നിവ ഒരിടത്ത് കാണിക്കൂ.",
    servicesKicker: "ഞങ്ങൾ നൽകുന്നത്",
    servicesTitle: "ഞങ്ങളുടെ സേവനങ്ങൾ",
    serviceText: "വ്യക്തമായ വിവരം, enquiry, എളുപ്പത്തിലുള്ള ബന്ധം എന്നിവയ്ക്കായി സേവന ബ്ലോക്കുകൾ.",
    findUs: "ഞങ്ങളെ കണ്ടെത്തൂ",
    contactTitle: "ബന്ധപ്പെടുക & സമയം",
    mapTitle: "Google Maps ൽ കാണൂ",
    gallery: "ഗാലറി",
    kicker: "ഒരു ക്ലാസിക് ബിസിനസ് സ്റ്റൈൽ",
    title: "വിശ്വാസം നിർമ്മിക്കൂ, കൂടുതൽ ലീഡ് നേടൂ.",
    description: "സേവനങ്ങൾ, സമയം, ഗാലറി, നേരിട്ടുള്ള ബന്ധം കാണിക്കാൻ ആധുനിക വെബ്സൈറ്റ്.",
    aboutKicker: "ബിസിനസിനെ കുറിച്ച്",
    aboutTitle: "ഗുണനിലവാരവും വിശ്വാസവും കൂടുന്നിടം",
    about: "പ്രാദേശിക ബിസിനസുകൾക്കായി രൂപകൽപ്പന ചെയ്ത ഡിസൈൻ, സേവനങ്ങൾ വ്യക്തമായി കാണിച്ച് ഉപഭോക്താവിന് എളുപ്പത്തിൽ ബന്ധപ്പെടാൻ സഹായിക്കുന്നു.",
    services: ["പ്രധാന സേവനം", "പ്രീമിയം സേവനം", "കൺസൾട്ടേഷൻ", "ബുക്കിംഗ് പിന്തുണ", "ഉപഭോക്തൃ സേവനം", "WhatsApp ലീഡ്"],
    stats: [["6+", "വർഷത്തെ പരിചയം"], ["12", "വിദഗ്ധ ടീം"], ["98%", "ഉപഭോക്തൃ സംതൃപ്തി"]],
    galleryTitle: "ബ്രാൻഡിന്റെ ഉള്ളിൽ",
    mapNote: "കോൾ, enquiry, booking, WhatsApp leads എന്നിവയ്ക്ക് അനുയോജ്യം.",
  }),
  Manipuri: createIndianLabels({
    callNow: "ꯀꯣꯜ ꯇꯧꯕꯤꯌꯨ",
    getStarted: "ꯍꯧꯕꯤꯌꯨ",
    seeServices: "ꯁꯔꯚꯤꯁ ꯌꯦꯡꯕꯤꯌꯨ",
    launchPackage: "ꯂꯧꯟꯆ ꯄꯦꯀꯦꯖ",
    doctorTitle: "ꯄ꯭ꯔꯣꯐꯥꯏꯜ ꯁꯦꯝꯂꯦ",
    doctorText: "ꯑꯦꯛꯁꯄꯔꯇ ꯏꯟꯐꯣ, ꯃꯇꯝ, ꯕꯨꯀꯤꯡ CTA ꯑꯃꯁꯨꯡ ꯊꯥꯖꯕ ꯑꯃꯗ ꯎꯠꯄꯤꯌꯨ।",
    servicesKicker: "ꯑꯩꯈꯣꯌꯅ ꯀꯔꯤ ꯄꯤꯕꯒꯦ",
    servicesTitle: "ꯑꯩꯈꯣꯌꯒꯤ ꯁꯔꯚꯤꯁ",
    serviceText: "ꯁꯦꯡꯕ ꯏꯟꯐꯣ, enquiry ꯑꯃꯁꯨꯡ ꯂꯥꯏꯅ ꯀꯟꯇꯦꯛꯇ ꯇꯧꯕꯒꯤ ꯁꯔꯚꯤꯁ ꯕ꯭ꯂꯣꯛ।",
    findUs: "ꯑꯩꯈꯣꯌꯕꯨ ꯊꯤꯕꯤꯌꯨ",
    contactTitle: "ꯀꯟꯇꯦꯛꯇ ꯑꯃꯁꯨꯡ ꯃꯇꯝ",
    mapTitle: "Google Maps ꯗ ꯌꯦꯡꯕꯤꯌꯨ",
    gallery: "ꯒꯦꯂꯔꯤ",
    kicker: "ꯀ꯭ꯂꯥꯁꯤꯛ ꯕꯤꯖꯅꯦꯁ ꯁ꯭ꯇꯥꯏꯜ",
    title: "ꯊꯥꯖꯕ ꯁꯦꯝꯃꯨ, ꯂꯤꯗ ꯍꯦꯟꯅ ꯐꯪꯎ।",
    description: "ꯁꯔꯚꯤꯁ, ꯃꯇꯝ, ꯒꯦꯂꯔꯤ ꯑꯃꯁꯨꯡ ꯗꯥꯏꯔꯦꯛꯇ ꯀꯟꯇꯦꯛꯇ ꯎꯠꯄꯤꯕꯒꯤ ꯋꯦꯕꯁꯥꯏꯇ।",
    aboutKicker: "ꯕꯤꯖꯅꯦꯁ ꯃꯔꯝꯗ",
    aboutTitle: "ꯀ꯭ꯕꯥꯂꯤꯇꯤ ꯑꯃꯁꯨꯡ ꯊꯥꯖꯕ ꯄꯨꯟꯅ ꯂꯩꯕ ꯃꯐꯝ",
    about: "ꯂꯣꯀꯦꯜ ꯕꯤꯖꯅꯦꯁꯁꯤꯡꯒꯤꯗꯃꯛ ꯁꯦꯝꯕ, ꯁꯔꯚꯤꯁ ꯁꯦꯡꯅ ꯎꯠꯄꯤꯕ ꯑꯃꯁꯨꯡ ꯀꯁꯇꯃꯔ ꯂꯥꯏꯅ ꯀꯟꯇꯦꯛꯇ ꯇꯧꯕ।",
    services: ["ꯃꯔꯨ ꯁꯔꯚꯤꯁ", "ꯄ꯭ꯔꯤꯃꯤꯌꯝ ꯁꯔꯚꯤꯁ", "ꯀꯟꯁꯜꯇꯦꯁꯟ", "ꯕꯨꯀꯤꯡ ꯁꯄꯣꯔꯇ", "ꯀꯁꯇꯃꯔ ꯁꯔꯚꯤꯁ", "WhatsApp ꯂꯤꯗ"],
    stats: [["6+", "ꯆꯍꯤꯒꯤ ꯑꯦꯛꯁꯄꯤꯔꯤꯌꯦꯟꯁ"], ["12", "ꯑꯦꯛꯁꯄꯔꯇ ꯇꯤꯝ"], ["98%", "ꯀꯁꯇꯃꯔ ꯁꯦꯇꯤꯁꯐꯦꯛꯁꯟ"]],
    galleryTitle: "ꯕ꯭ꯔꯥꯟꯗꯒꯤ ꯃꯅꯨꯡ",
    mapNote: "ꯀꯣꯜ, enquiry, booking ꯑꯃꯁꯨꯡ WhatsApp leads ꯒꯤꯗꯃꯛ।",
  }),
  Marathi: createIndianLabels({
    callNow: "कॉल करा",
    getStarted: "सुरू करा",
    seeServices: "सेवा पहा",
    launchPackage: "लॉन्च पॅकेज",
    doctorTitle: "प्रोफाइल तयार",
    doctorText: "तज्ज्ञ माहिती, वेळ, बुकिंग CTA आणि विश्वास एका ठिकाणी दाखवा.",
    servicesKicker: "आम्ही काय देतो",
    servicesTitle: "आमच्या सेवा",
    serviceText: "स्पष्ट माहिती, enquiry आणि सोपा संपर्क यासाठी तयार सेवा ब्लॉक.",
    findUs: "आम्हाला शोधा",
    contactTitle: "संपर्क आणि वेळ",
    mapTitle: "Google Maps वर पहा",
    gallery: "गॅलरी",
    kicker: "एक क्लासिक बिझनेस स्टाइल",
    title: "विश्वास तयार करा, जास्त लीड मिळवा.",
    description: "सेवा, वेळ, गॅलरी आणि थेट संपर्क दाखवण्यासाठी आधुनिक वेबसाइट.",
    aboutKicker: "बिझनेसबद्दल",
    aboutTitle: "जिथे गुणवत्ता आणि विश्वास भेटतात",
    about: "स्थानिक बिझनेससाठी तयार केलेले डिझाइन, जे सेवा स्पष्ट दाखवते आणि ग्राहकांना सहज संपर्क करू देते.",
    services: ["मुख्य सेवा", "प्रीमियम सेवा", "सल्ला", "बुकिंग सपोर्ट", "ग्राहक सेवा", "WhatsApp लीड"],
    stats: [["6+", "वर्षांचा अनुभव"], ["12", "तज्ज्ञ टीम"], ["98%", "ग्राहक समाधान"]],
    galleryTitle: "ब्रँडची झलक",
    mapNote: "कॉल, enquiry, booking आणि WhatsApp leads साठी योग्य.",
  }),
  Nepali: createIndianLabels({
    callNow: "कल गर्नुहोस्",
    getStarted: "सुरु गर्नुहोस्",
    seeServices: "सेवा हेर्नुहोस्",
    launchPackage: "लन्च प्याकेज",
    doctorTitle: "प्रोफाइल तयार",
    doctorText: "विशेषज्ञ विवरण, समय, बुकिङ CTA र विश्वास एउटै ठाउँमा देखाउनुहोस्।",
    servicesKicker: "हामी के दिन्छौँ",
    servicesTitle: "हाम्रा सेवाहरू",
    serviceText: "स्पष्ट जानकारी, enquiry र सजिलो सम्पर्कका लागि तयार सेवा ब्लक।",
    findUs: "हामीलाई भेट्नुहोस्",
    contactTitle: "सम्पर्क र समय",
    mapTitle: "Google Maps मा हेर्नुहोस्",
    gallery: "ग्यालरी",
    kicker: "एक क्लासिक व्यवसाय शैली",
    title: "विश्वास बनाउनुहोस्, बढी लिड पाउनुहोस्।",
    description: "सेवा, समय, ग्यालरी र प्रत्यक्ष सम्पर्क देखाउन बनाइएको आधुनिक वेबसाइट।",
    aboutKicker: "व्यवसाय बारे",
    aboutTitle: "जहाँ गुणस्तर र विश्वास भेटिन्छ",
    about: "स्थानीय व्यवसायका लागि बनाइएको डिजाइन, जसले सेवा स्पष्ट देखाउँछ र ग्राहकलाई छिटो सम्पर्क गर्न मद्दत गर्छ।",
    services: ["मुख्य सेवा", "प्रिमियम सेवा", "परामर्श", "बुकिङ सपोर्ट", "ग्राहक सेवा", "WhatsApp लिड"],
    stats: [["6+", "वर्षको अनुभव"], ["12", "विशेषज्ञ टोली"], ["98%", "ग्राहक सन्तुष्टि"]],
    galleryTitle: "ब्रान्ड भित्र",
    mapNote: "कल, enquiry, booking र WhatsApp leads का लागि उपयुक्त।",
  }),
  Odia: createIndianLabels({
    callNow: "କଲ୍ କରନ୍ତୁ",
    getStarted: "ଆରମ୍ଭ କରନ୍ତୁ",
    seeServices: "ସେବା ଦେଖନ୍ତୁ",
    launchPackage: "ଲଞ୍ଚ ପ୍ୟାକେଜ୍",
    doctorTitle: "ପ୍ରୋଫାଇଲ୍ ପ୍ରସ୍ତୁତ",
    doctorText: "ବିଶେଷଜ୍ଞ ତଥ୍ୟ, ସମୟ, ବୁକିଂ CTA ଓ ବିଶ୍ୱାସ ଏକ ଜାଗାରେ ଦେଖାନ୍ତୁ।",
    servicesKicker: "ଆମେ କଣ ଦେଉଛୁ",
    servicesTitle: "ଆମର ସେବା",
    serviceText: "ସ୍ପଷ୍ଟ ତଥ୍ୟ, enquiry ଓ ସହଜ ସମ୍ପର୍କ ପାଇଁ ସେବା ବ୍ଲକ୍।",
    findUs: "ଆମକୁ ଖୋଜନ୍ତୁ",
    contactTitle: "ସମ୍ପର୍କ ଓ ସମୟ",
    mapTitle: "Google Maps ରେ ଦେଖନ୍ତୁ",
    gallery: "ଗ୍ୟାଲେରୀ",
    kicker: "ଏକ କ୍ଲାସିକ୍ ବିଜନେସ୍ ଶୈଳୀ",
    title: "ବିଶ୍ୱାସ ଗଢ଼ନ୍ତୁ, ଅଧିକ ଲିଡ୍ ପାଆନ୍ତୁ।",
    description: "ସେବା, ସମୟ, ଗ୍ୟାଲେରୀ ଓ ସିଧା ସମ୍ପର୍କ ଦେଖାଇବାକୁ ଆଧୁନିକ ୱେବସାଇଟ୍।",
    aboutKicker: "ବିଜନେସ୍ ବିଷୟରେ",
    aboutTitle: "ଯେଉଁଠାରେ ଗୁଣ ଓ ବିଶ୍ୱାସ ମିଳେ",
    about: "ସ୍ଥାନୀୟ ବିଜନେସ୍ ପାଇଁ ତିଆରି ଡିଜାଇନ୍, ଯାହା ସେବାକୁ ସ୍ପଷ୍ଟ କରେ ଓ ଗ୍ରାହକଙ୍କୁ ସହଜରେ ସମ୍ପର୍କ କରାଏ।",
    services: ["ମୁଖ୍ୟ ସେବା", "ପ୍ରିମିୟମ୍ ସେବା", "ପରାମର୍ଶ", "ବୁକିଂ ସପୋର୍ଟ", "ଗ୍ରାହକ ସେବା", "WhatsApp ଲିଡ୍"],
    stats: [["6+", "ବର୍ଷର ଅନୁଭବ"], ["12", "ବିଶେଷଜ୍ଞ ଟିମ୍"], ["98%", "ଗ୍ରାହକ ସନ୍ତୁଷ୍ଟି"]],
    galleryTitle: "ବ୍ରାଣ୍ଡର ଝଲକ",
    mapNote: "କଲ୍, enquiry, booking ଓ WhatsApp leads ପାଇଁ ଉପଯୁକ୍ତ।",
  }),
  Punjabi: createIndianLabels({
    callNow: "ਕਾਲ ਕਰੋ",
    getStarted: "ਸ਼ੁਰੂ ਕਰੋ",
    seeServices: "ਸੇਵਾਵਾਂ ਵੇਖੋ",
    launchPackage: "ਲਾਂਚ ਪੈਕੇਜ",
    doctorTitle: "ਪ੍ਰੋਫਾਈਲ ਤਿਆਰ",
    doctorText: "ਮਾਹਿਰ ਜਾਣਕਾਰੀ, ਸਮਾਂ, ਬੁਕਿੰਗ CTA ਅਤੇ ਭਰੋਸਾ ਇੱਕ ਥਾਂ ਦਿਖਾਓ।",
    servicesKicker: "ਅਸੀਂ ਕੀ ਦਿੰਦੇ ਹਾਂ",
    servicesTitle: "ਸਾਡੀਆਂ ਸੇਵਾਵਾਂ",
    serviceText: "ਸਪਸ਼ਟ ਜਾਣਕਾਰੀ, enquiry ਅਤੇ ਆਸਾਨ ਸੰਪਰਕ ਲਈ ਸੇਵਾ ਬਲਾਕ।",
    findUs: "ਸਾਨੂੰ ਲੱਭੋ",
    contactTitle: "ਸੰਪਰਕ ਅਤੇ ਸਮਾਂ",
    mapTitle: "Google Maps ਤੇ ਵੇਖੋ",
    gallery: "ਗੈਲਰੀ",
    kicker: "ਇੱਕ ਕਲਾਸਿਕ ਬਿਜ਼ਨਸ ਸਟਾਈਲ",
    title: "ਭਰੋਸਾ ਬਣਾਓ, ਹੋਰ ਲੀਡ ਪਾਓ।",
    description: "ਸੇਵਾਵਾਂ, ਸਮਾਂ, ਗੈਲਰੀ ਅਤੇ ਸਿੱਧਾ ਸੰਪਰਕ ਦਿਖਾਉਣ ਲਈ ਆਧੁਨਿਕ ਵੈਬਸਾਈਟ।",
    aboutKicker: "ਬਿਜ਼ਨਸ ਬਾਰੇ",
    aboutTitle: "ਜਿੱਥੇ ਗੁਣਵੱਤਾ ਅਤੇ ਭਰੋਸਾ ਮਿਲਦੇ ਹਨ",
    about: "ਸਥਾਨਕ ਬਿਜ਼ਨਸ ਲਈ ਬਣਾਇਆ ਡਿਜ਼ਾਈਨ, ਜੋ ਸੇਵਾਵਾਂ ਸਪਸ਼ਟ ਦਿਖਾਉਂਦਾ ਹੈ ਅਤੇ ਗਾਹਕ ਨੂੰ ਆਸਾਨ ਸੰਪਰਕ ਦਿੰਦਾ ਹੈ।",
    services: ["ਮੁੱਖ ਸੇਵਾ", "ਪ੍ਰੀਮੀਅਮ ਸੇਵਾ", "ਸਲਾਹ", "ਬੁਕਿੰਗ ਸਹਾਇਤਾ", "ਗਾਹਕ ਸੇਵਾ", "WhatsApp ਲੀਡ"],
    stats: [["6+", "ਸਾਲਾਂ ਦਾ ਤਜਰਬਾ"], ["12", "ਮਾਹਿਰ ਟੀਮ"], ["98%", "ਗਾਹਕ ਸੰਤੁਸ਼ਟੀ"]],
    galleryTitle: "ਬ੍ਰਾਂਡ ਦੀ ਝਲਕ",
    mapNote: "ਕਾਲ, enquiry, booking ਅਤੇ WhatsApp leads ਲਈ ਠੀਕ।",
  }),
  Sanskrit: createIndianLabels({
    callNow: "आह्वानं कुरुत",
    getStarted: "आरभत",
    seeServices: "सेवाः पश्यत",
    launchPackage: "प्रारम्भ-पुटकः",
    doctorTitle: "प्रोफाइलं सिद्धम्",
    doctorText: "विशेषज्ञसूचना, समयः, बुकिंग CTA च विश्वासः एकत्र दर्श्यते।",
    servicesKicker: "वयं किं दद्मः",
    servicesTitle: "अस्माकं सेवाः",
    serviceText: "स्पष्टसूचना, enquiry च सरलसम्पर्काय सेवा-विभागाः।",
    findUs: "अस्मान् अन्विष्यत",
    contactTitle: "सम्पर्कः समयश्च",
    mapTitle: "Google Maps मध्ये पश्यत",
    gallery: "चित्रशाला",
    kicker: "क्लासिक-व्यवसाय-शैली",
    title: "विश्वासं निर्मात, अधिकान् लीड् प्राप्नुत।",
    description: "सेवाः, समयः, चित्रशाला च प्रत्यक्षसम्पर्कं दर्शयितुं आधुनिकं जालपृष्ठम्।",
    aboutKicker: "व्यवसायस्य विषये",
    aboutTitle: "यत्र गुणवत्ता विश्वासश्च मिलतः",
    about: "स्थानिकव्यवसायाय निर्मितं रूपांकनम्, येन सेवाः स्पष्टाः भवन्ति ग्राहकाः च सरलतया सम्पर्कं कुर्वन्ति।",
    services: ["मुख्य सेवा", "प्रीमियम सेवा", "परामर्शः", "बुकिंग-सहायता", "ग्राहक सेवा", "WhatsApp लीड"],
    stats: [["6+", "वर्षाणाम् अनुभवः"], ["12", "विशेषज्ञदलम्"], ["98%", "ग्राहकसन्तोषः"]],
    galleryTitle: "ब्राण्डस्य झलकः",
    mapNote: "आह्वान, enquiry, booking च WhatsApp leads कृते उपयुक्तम्।",
  }),
  Santali: createIndianLabels({
    callNow: "ᱠᱚᱞ ᱢᱮ",
    getStarted: "ᱮᱦᱚᱵ ᱢᱮ",
    seeServices: "ᱥᱮᱵᱟ ᱧᱮᱞ ᱢᱮ",
    launchPackage: "ᱞᱚᱧᱪ ᱯᱮᱠᱮᱡ",
    doctorTitle: "ᱯᱨᱚᱯᱷᱟᱭᱞ ᱛᱮᱭᱟᱨ",
    doctorText: "ᱵᱤᱥᱮᱥ ᱵᱟᱵᱚᱛ, ᱚᱠᱛᱚ, ᱵᱩᱠᱤᱝ CTA ᱟᱨ ᱵᱤᱥᱣᱟᱥ ᱢᱤᱫ ᱴᱷᱟᱶ ᱨᱮ ᱫᱮᱠᱷᱟᱣ ᱢᱮ।",
    servicesKicker: "ᱟᱞᱮ ᱪᱮᱫ ᱮᱢᱟ",
    servicesTitle: "ᱟᱞᱮᱭᱟᱜ ᱥᱮᱵᱟ",
    serviceText: "ᱥᱟᱯᱷᱟ ᱵᱟᱵᱚᱛ, enquiry ᱟᱨ ᱥᱚᱦᱚᱡ ᱡᱚᱜᱟᱡᱚᱜ ᱞᱟᱹᱜᱤᱫ ᱥᱮᱵᱟ ᱵᱞᱚᱠ।",
    findUs: "ᱟᱞᱮ ᱯᱟᱱᱛᱮ ᱢᱮ",
    contactTitle: "ᱡᱚᱜᱟᱡᱚᱜ ᱟᱨ ᱚᱠᱛᱚ",
    mapTitle: "Google Maps ᱨᱮ ᱧᱮᱞ ᱢᱮ",
    gallery: "ᱜᱮᱞᱟᱨᱤ",
    kicker: "ᱢᱤᱫ ᱠᱞᱟᱥᱤᱠ ᱵᱤᱡᱽᱱᱮᱥ ᱥᱴᱟᱭᱞ",
    title: "ᱵᱤᱥᱣᱟᱥ ᱵᱮᱱᱟᱣ ᱢᱮ, ᱟᱨᱦᱚᱸ ᱞᱤᱰ ᱧᱟᱢ ᱢᱮ।",
    description: "ᱥᱮᱵᱟ, ᱚᱠᱛᱚ, ᱜᱮᱞᱟᱨᱤ ᱟᱨ ᱥᱚᱡᱷᱟ ᱡᱚᱜᱟᱡᱚᱜ ᱫᱮᱠᱷᱟᱣ ᱞᱟᱹᱜᱤᱫ ᱣᱮᱵᱽᱥᱟᱭᱤᱴ।",
    aboutKicker: "ᱵᱤᱡᱽᱱᱮᱥ ᱵᱟᱵᱚᱛ",
    aboutTitle: "ᱡᱟᱦᱟᱸ ᱜᱩᱱ ᱟᱨ ᱵᱤᱥᱣᱟᱥ ᱢᱮᱞᱟᱜᱼᱟ",
    about: "ᱞᱚᱠᱟᱞ ᱵᱤᱡᱽᱱᱮᱥ ᱞᱟᱹᱜᱤᱫ ᱫᱤᱡᱟᱭᱤᱱ, ᱡᱟᱦᱟᱸ ᱥᱮᱵᱟ ᱥᱟᱯᱷᱟ ᱫᱮᱠᱷᱟᱣ ᱟᱨ ᱠᱟᱥᱴᱚᱢᱚᱨ ᱥᱚᱦᱚᱡ ᱡᱚᱜᱟᱡᱚᱜ ᱠᱚᱨᱟᱣ।",
    services: ["ᱢᱩᱬ ᱥᱮᱵᱟ", "ᱯᱨᱤᱢᱤᱭᱟᱢ ᱥᱮᱵᱟ", "ᱥᱟᱞᱟᱦ", "ᱵᱩᱠᱤᱝ ᱥᱟᱯᱚᱨᱴ", "ᱠᱟᱥᱴᱚᱢᱚᱨ ᱥᱮᱵᱟ", "WhatsApp ᱞᱤᱰ"],
    stats: [["6+", "ᱵᱚᱪᱷᱚᱨ ᱚᱵᱷᱤᱡᱽᱱᱚᱛᱟ"], ["12", "ᱵᱤᱥᱮᱥ ᱴᱤᱢ"], ["98%", "ᱠᱟᱥᱴᱚᱢᱚᱨ ᱥᱟᱱᱛᱩᱥᱴᱤ"]],
    galleryTitle: "ᱵᱨᱟᱱᱰ ᱨᱮᱭᱟᱜ ᱡᱷᱟᱞᱚᱠ",
    mapNote: "ᱠᱚᱞ, enquiry, booking ᱟᱨ WhatsApp leads ᱞᱟᱹᱜᱤᱫ।",
  }),
  Sindhi: createIndianLabels({
    callNow: "ڪال ڪريو",
    getStarted: "شروع ڪريو",
    seeServices: "خدمتون ڏسو",
    launchPackage: "لانچ پيڪيج",
    doctorTitle: "پروفائل تيار",
    doctorText: "ماهر ڄاڻ، وقت، بڪنگ CTA ۽ اعتماد هڪ هنڌ ڏيکاريو.",
    servicesKicker: "اسان ڇا ڏيون ٿا",
    servicesTitle: "اسان جون خدمتون",
    serviceText: "صاف ڄاڻ، enquiry ۽ آسان رابطو لاءِ خدمت بلاڪ.",
    findUs: "اسان کي ڳوليو",
    contactTitle: "رابطو ۽ وقت",
    mapTitle: "Google Maps تي ڏسو",
    gallery: "گيلري",
    kicker: "هڪ ڪلاسڪ بزنس اسٽائل",
    title: "اعتماد ٺاهيو، وڌيڪ ليڊ حاصل ڪريو.",
    description: "خدمتون، وقت، گيلري ۽ سڌو رابطو ڏيکارڻ لاءِ جديد ويب سائيٽ.",
    aboutKicker: "بزنس بابت",
    aboutTitle: "جتي معيار ۽ اعتماد ملن ٿا",
    about: "مقامي بزنس لاءِ ٺاهيل ڊيزائن، جيڪا خدمتون صاف ڏيکاري ۽ گراهڪ کي آسان رابطو ڏئي.",
    services: ["مکيه خدمت", "پريميئم خدمت", "صلاح", "بڪنگ سپورٽ", "گراهڪ خدمت", "WhatsApp ليڊ"],
    stats: [["6+", "سال جو تجربو"], ["12", "ماهر ٽيم"], ["98%", "گراهڪ خوشي"]],
    galleryTitle: "برانڊ جي جھلڪ",
    mapNote: "ڪال، enquiry، booking ۽ WhatsApp leads لاءِ مناسب.",
  }),
  Tamil: createIndianLabels({
    callNow: "அழைக்கவும்",
    getStarted: "தொடங்கவும்",
    seeServices: "சேவைகள் பார்க்க",
    launchPackage: "லாஞ்ச் பேக்கேஜ்",
    doctorTitle: "ப்ரொஃபைல் தயார்",
    doctorText: "நிபுணர் தகவல், நேரம், புக்கிங் CTA மற்றும் நம்பிக்கை ஒரே இடத்தில் காட்டுங்கள்.",
    servicesKicker: "நாங்கள் வழங்குவது",
    servicesTitle: "எங்கள் சேவைகள்",
    serviceText: "தெளிவான தகவல், enquiry மற்றும் எளிய தொடர்புக்கான சேவை ப்ளாக்.",
    findUs: "எங்களை கண்டுபிடிக்க",
    contactTitle: "தொடர்பு & நேரம்",
    mapTitle: "Google Maps இல் பார்க்க",
    gallery: "கேலரி",
    kicker: "ஒரு கிளாசிக் பிசினஸ் ஸ்டைல்",
    title: "நம்பிக்கை உருவாக்குங்கள், அதிக லீட்கள் பெறுங்கள்.",
    description: "சேவைகள், நேரம், கேலரி மற்றும் நேரடி தொடர்பை காட்ட நவீன இணையதளம்.",
    aboutKicker: "பிசினஸ் பற்றி",
    aboutTitle: "தரம் மற்றும் நம்பிக்கை இணையும் இடம்",
    about: "உள்ளூர் பிசினஸுக்காக வடிவமைக்கப்பட்டது, சேவைகள் தெளிவாக தெரியும் மற்றும் வாடிக்கையாளர் எளிதில் தொடர்பு கொள்வார்.",
    services: ["முக்கிய சேவை", "பிரீமியம் சேவை", "ஆலோசனை", "புக்கிங் ஆதரவு", "வாடிக்கையாளர் சேவை", "WhatsApp லீட்"],
    stats: [["6+", "ஆண்டுகள் அனுபவம்"], ["12", "நிபுணர் குழு"], ["98%", "வாடிக்கையாளர் திருப்தி"]],
    galleryTitle: "பிராண்டின் காட்சி",
    mapNote: "அழைப்பு, enquiry, booking மற்றும் WhatsApp leads க்கு பொருத்தம்.",
  }),
  Telugu: createIndianLabels({
    callNow: "కాల్ చేయండి",
    getStarted: "ప్రారంభించండి",
    seeServices: "సేవలు చూడండి",
    launchPackage: "లాంచ్ ప్యాకేజ్",
    doctorTitle: "ప్రొఫైల్ సిద్ధం",
    doctorText: "నిపుణుల సమాచారం, సమయం, బుకింగ్ CTA మరియు నమ్మకాన్ని ఒకచోట చూపండి.",
    servicesKicker: "మేము ఏమి ఇస్తాము",
    servicesTitle: "మా సేవలు",
    serviceText: "స్పష్టమైన సమాచారం, enquiry మరియు సులభ సంప్రదింపుల కోసం సేవా బ్లాక్.",
    findUs: "మమ్మల్ని కనుగొనండి",
    contactTitle: "సంప్రదింపు & సమయం",
    mapTitle: "Google Maps లో చూడండి",
    gallery: "గ్యాలరీ",
    kicker: "ఒక క్లాసిక్ బిజినెస్ స్టైల్",
    title: "నమ్మకం పెంచండి, ఎక్కువ లీడ్స్ పొందండి.",
    description: "సేవలు, సమయం, గ్యాలరీ మరియు నేరుగా సంప్రదింపును చూపడానికి ఆధునిక వెబ్‌సైట్.",
    aboutKicker: "బిజినెస్ గురించి",
    aboutTitle: "నాణ్యత మరియు నమ్మకం కలిసే చోటు",
    about: "స్థానిక బిజినెస్ కోసం రూపొందించిన డిజైన్, సేవలు స్పష్టంగా కనిపించి కస్టమర్ సులభంగా సంప్రదించగలడు.",
    services: ["ముఖ్య సేవ", "ప్రీమియం సేవ", "సలహా", "బుకింగ్ సపోర్ట్", "కస్టమర్ సేవ", "WhatsApp లీడ్"],
    stats: [["6+", "ఏళ్ల అనుభవం"], ["12", "నిపుణుల టీమ్"], ["98%", "కస్టమర్ సంతృప్తి"]],
    galleryTitle: "బ్రాండ్ లోపలి చూపు",
    mapNote: "కాల్, enquiry, booking మరియు WhatsApp leads కు సరైనది.",
  }),
  Urdu: createIndianLabels({
    callNow: "کال کریں",
    getStarted: "شروع کریں",
    seeServices: "خدمات دیکھیں",
    launchPackage: "لانچ پیکیج",
    doctorTitle: "پروفائل تیار",
    doctorText: "ماہر معلومات، وقت، بکنگ CTA اور اعتماد ایک جگہ دکھائیں۔",
    servicesKicker: "ہم کیا دیتے ہیں",
    servicesTitle: "ہماری خدمات",
    serviceText: "صاف معلومات، enquiry اور آسان رابطے کے لیے خدمت بلاک۔",
    findUs: "ہمیں تلاش کریں",
    contactTitle: "رابطہ اور وقت",
    mapTitle: "Google Maps پر دیکھیں",
    gallery: "گیلری",
    kicker: "ایک کلاسک بزنس اسٹائل",
    title: "اعتماد بنائیں، زیادہ لیڈ حاصل کریں۔",
    description: "خدمات، وقت، گیلری اور براہ راست رابطہ دکھانے کے لیے جدید ویب سائٹ۔",
    aboutKicker: "بزنس کے بارے میں",
    aboutTitle: "جہاں معیار اور اعتماد ملتے ہیں",
    about: "مقامی بزنس کے لیے ڈیزائن، تاکہ خدمات صاف نظر آئیں اور گاہک آسانی سے رابطہ کر سکے۔",
    services: ["اہم خدمت", "پریمیم خدمت", "مشورہ", "بکنگ سپورٹ", "گاہک خدمت", "WhatsApp لیڈ"],
    stats: [["6+", "سال کا تجربہ"], ["12", "ماہر ٹیم"], ["98%", "گاہک اطمینان"]],
    galleryTitle: "برانڈ کی جھلک",
    mapNote: "کال، enquiry، booking اور WhatsApp leads کے لیے مناسب۔",
  }),
});

function localizeBusiness(business, labels) {
  if (!labels?.content) return business;
  return { ...business, ...labels.content };
}

export default function TemplateOne({ template, accent, font, relatedHref, themeOverride, language }) {
  const theme = { ...(template.theme || {}), ...(themeOverride || {}) };
  const labels = LABELS[language] || LABELS.English;
  const business = localizeBusiness({ ...defaultBusiness, ...(template.business || {}) }, labels);
  const services = business.services?.length ? business.services : defaultBusiness.services;
  const stats = business.stats?.length ? business.stats : defaultBusiness.stats;

  return (
    <div
      className={`lite-template is-${template.category}`}
      style={{
        "--lite-accent": accent || template.accent,
        "--lite-bg": theme.bg || "#fffaf4",
        "--lite-surface": theme.surface || "#ffffff",
        "--lite-panel": theme.panel || "#f7efe6",
        "--lite-card": theme.card || "#ffffff",
        "--lite-ink": theme.ink || "#1d1b18",
        "--lite-muted": theme.muted || "#746b61",
        "--lite-soft": theme.soft || "#f3e7da",
        "--lite-line": theme.line || "rgba(29,27,24,.12)",
        "--lite-on-accent": theme.onAccent || "#ffffff",
        "--lite-radius": theme.radius || "7px",
        "--lite-font": getFontFamily(font || template.font),
        "--lite-heading-font": getHeadingFont(font || template.font),
      }}
    >
      <TemplateStyles template={template} />
      <Nav business={business} relatedHref={relatedHref} labels={labels} />
      <Hero business={business} template={template} labels={labels} />
      <About business={business} stats={stats} />
      <Services services={services} icon={template.icon} labels={labels} />
      <Gallery title={business.galleryTitle || `Inside ${business.brandName}`} labels={labels} />
      <Contact business={business} labels={labels} />
      <FloatingWhatsApp business={business} />
    </div>
  );
}
